### ISSUE TITLE
Trying to run within node-webkit fails

### ISSUE THREAD

**Issue by ddankwerth** [agracio/edge-js#1]
Thanks for putting edge-js up, I am using it with node 8.x.

I tried to use it with nw.js (node-webkit) but i get an error : 
uncaught Error: Invalid access to memory location.
\\?\C:\temp\nw\sample\node_modules\edge-js\lib\native\win32\x64\8.1.2\edge_nativeclr.node
    at Object.Module._extensions..node (module.js:640:18)
    at Module.load (module.js:527:32)
    at tryModuleLoad (module.js:490:12)
    at Function.Module._load (module.js:482:3)
    at Module.require (module.js:537:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\temp\nw\sample\node_modules\edge-js\lib\edge.js:53:8)
    at Module._compile (module.js:593:30)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:527:32)

Any idea how to solve this ?
Thanks.

**Comment by agracio** [comment]
Not sure, but the error looks similar to errors you would get when trying to use edge with electron. 
Are you getting the same error when trying to use standard `edge` npm with node 7.x?

**Comment by ddankwerth** [comment]
node-webkit comes bundled with node 8.x so i cant really check it.

**Comment by agracio** [comment]
Had a quick look at node-webkit and it appears that it bundles a build of chromium similar to electron. This likely means that it is dependant on a very specific version of node that it is built on. Since `edge-js` is built with 8.1.2 can you try v0.23.3 of node-webkit, it uses the same node version.

**Comment by ddankwerth** [comment]
Thanks for your reply, sadly, same error, i installed nw 23.3 as suggested , changed my node from 8.1.4 to 8.1.2 , removed edge-js, re addeded it 
executing node scripts/helloworld.js works fine 
running node-webkit with an index.html that loads scripts/helloworld.js gets the error above

**Comment by agracio** [comment]
On electron you would either use `electron-edge` instead of edge module or `electron-rebuild` to rebuild your node modules for correct version of node. I think https://github.com/nwjs/nw-gyp offers similar functionality, give it a try.

**Comment by ddankwerth** [comment]
Hmmm , tried that too, followed their nw-gyp instruction and got multiple
  C:\Users\user\.nw-gyp\0.23.3\deps\v8\include\v8.h(4041): error C2664:
 'std::pair<std::unique_ptr<const uint8_t [],
std::default_delete<_Ty>>,std::size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::size_t> &&)': 
cannot convert argument 1 from 'nullptr' to 'nullptr &&' [C:\temp\nw\sample\node_modules\edgejs\build\edge_nativeclr.vcxproj]

**Comment by agracio** [comment]
The problem is with nw.js 0.23.x, version 0.22.3 builds fine.
I think after nw-gyp build you would need to move files from `build/release` to appropriate `lib/` folder, but give it a try.

**Comment by ddankwerth** [comment]
Thanks, with that version edge-js does indeed build successfully, however, still would not run.
I do both npm rebuild (which "installs" the built version) or copy by hand and it still wouldnt work 
After copying the edge_xxxx.node and running i get : 
Error: The specified module could not be found.
Error: The specified module could not be found.
\\?\C:\temp\nw\sample\node_modules\edge-js\lib\native\win32\x64\8.1.2\edge_nativ
eclr.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\temp\nw\sample\node_modules\edge-js\lib\edge.js:55
:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

Same when i do npm rebuild

**Comment by agracio** [comment]
I'm out of ideas. If its a new project you could consider using electron instead, otherwise does not look like you will be able to use edge.
If you create a repo with test project I could take a look and see if i can come up with some kind of solution, but do not hold your breath, looks like this is a a serious problem.

**Comment by M90K7** [comment]
Please add right solution to build edge-js module for nwjs platform ...

**Comment by agracio** [comment]
Currently there are no plans to support nwjs. You can tale a look a `electron-edge-js` build configuration and the specific changes it has for Electron and try and  come up with solution for nwjs.

**Comment by choukui** [comment]
我也遇到同样的问题，nwjs下报错 Module did not self-register

**Comment by agracio** [comment]
As per previous comment, `edje-js` does not support `nwjs` and there are no plans to support it
