### ISSUE TITLE
Building with node v8.9.0(LTS)

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [agracio/edge-js#10]
I'm trying to build with using node v8.9.0 and am getting an error when trying to run:
"%NODEEXE%" "%GYP%" configure --msvs_version=2017

With Node v8.2.1, I can use:
"%NODEEXE%" "%GYP%" configure --msvs_version=2015

But, node 8.9.0 fails with "cannot convert argument 1 from 'nullptr' to 'nullptr &&'" -- I suspect that I *need* 2017 for newer versions of node.

Are there any additional setup steps not listed in the markdown needed to build for VS2017 && newer versions of node?

Error from "%NODEEXE%" "%GYP%" configure --msvs_version=2017 

gyp info spawn args   'D:\\Working\\edge-js\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Emerson\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--msvs_version=2017"
gyp ERR! cwd D:\Working\edge-js
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by agracio** [comment]
You need VS2017 tools, nothing else. I usually build using `tools\build.bat` command. So something like `build release 8.9.0` works for me.

**Comment by Michael-Tajmajer-Emrsn** [comment]
What version of node-gyp are you using?

I run and see this:
D:\Working\edge-js>tools\build.bat release 8.9.0
Downloading node.exe x86 8.9.0...
Trying download from http://nodejs.org/dist/v8.9.0/node.exe
HTTP 301
Trying download from http://nodejs.org/dist/v8.9.0/win-x86/node.exe
HTTP 200
Building edge.node release for node.js x86 v8.9.0
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.0 | win32 | ia32
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\Emerson\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2017',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Working\\edge-js\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Emerson\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Emerson\\.node-gyp\\8.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Emerson\\.node-gyp\\8.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Emerson\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Emerson\\.node-gyp\\8.9.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Working\\edge-js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Working\\edge-js\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Working\\edge-js\\lib\\native\\win32\\ia32\\8.9.0\\node.exe" "C:\\Users\\Emerson\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--msvs_version=2017" "-release"
gyp ERR! cwd D:\Working\edge-js
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Error building edge.node release for node.js x86 v8.9.0

**Comment by agracio** [comment]
v3.6.2. Your error indicates that you missing VS2017 build tools.
```
File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
generator_flags.get('msvs_version', 'auto'))
File "C:\Users\Emerson\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
```

**Comment by Michael-Tajmajer-Emrsn** [comment]
I've run:
npm install --global windows-build-tools

Are there any other steps?

**Comment by agracio** [comment]
I believe you need these [Build Tools for Visual Studio 2017](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017)

**Comment by Michael-Tajmajer-Emrsn** [comment]
I have them installed as well as a full version of VS2017 -- what version of the WIndows 10 SDK do you have installed?

![image](https://user-images.githubusercontent.com/26899055/32459063-12b49a08-c2f4-11e7-990e-2e5c51d43faa.png)

**Comment by agracio** [comment]
If I remember correctly it was Windows 8.1 SDK that did the trick, and I know that it does not make any sense.

**Comment by Michael-Tajmajer-Emrsn** [comment]
I could not get it to work, I ended up modifying c:\Users\Use]\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py

And adding:
      '2017': VisualStudioVersion('2017',
                                  'Visual Studio 2017',
                                  solution_version='12.00',
                                  project_version='14.0',
                                  flat_sln=False,
                                  uses_vcxproj=True,
                                  path=path,
                                  sdk_based=sdk_based,
                                  default_toolset='v141'),

To the versions collection -- the key is having the toolset set to 141 - that makes things work :-)

**Comment by agracio** [comment]
Just checked mine and there is no 2017 there...

**Comment by Michael-Tajmajer-Emrsn** [comment]
I have no clue how your build is working -- I needed build toolset set to v141 to build without errors.

**Comment by agracio** [comment]
This is making less and less sense now, I just ran `build release 8.9.0` and here is part of console output:
```
gyp info spawn args   'msvs_version=2015',
```

**Comment by Michael-Tajmajer-Emrsn** [comment]
Perhaps you have an environment variable set?

**Comment by Michael-Tajmajer-Emrsn** [comment]
oops, reopening

**Comment by agracio** [comment]
And I get the same 
```
gyp info spawn args   'msvs_version=2015',
```
when i run `"%NODEEXE%" "%GYP%" configure --msvs_version=2017`

But if I change to `--msvs_version=2015` in build.bat 8.9.0 no longer builds...

**Comment by Michael-Tajmajer-Emrsn** [comment]
Check your c:\Users\UserName\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py

Maybe it was nodified?

**Comment by agracio** [comment]
I havent touched it myself and 'date modified' on it same as all the other file i.e. install date.

**Comment by Michael-Tajmajer-Emrsn** [comment]
When you build node are you using VS2017?

![image](https://user-images.githubusercontent.com/26899055/32465811-68f3b26c-c30a-11e7-8ae6-9ccc1d9fe935.png)

**Comment by Michael-Tajmajer-Emrsn** [comment]
Oops open.

**Comment by agracio** [comment]
It happens too fast for me to see command line. I just published version 9.0.1 that replaces Node.js v8.8.1 with v8.9.0.

**Comment by Michael-Tajmajer-Emrsn** [comment]
All I can think of is that you have a different version of node-gyp and somehow you are using the v141 tools.

I'm going to assume that node-gyp will get updated to use that toolset at some time and this will no longer be an issue :-)

**Comment by cobarx** [comment]
Electron just updated to 1.8.2, which packages with Node 8.2.1. I'm running into the same issue trying to build on it. Any chance you could publish a 8.2.1 binary?

**Comment by agracio** [comment]
To build for Eelectron you also need to use special build flags. There is an Electron specific version that addresses those issues: https://github.com/agracio/electron-edge-js

**Comment by cobarx** [comment]
I had no idea that existed, thanks for the heads up. It worked great.
