### ISSUE TITLE
NodeJS v14.x support ?

### ISSUE THREAD

**Issue by fforjan** [agracio/edge-js#100]
Dear all, 

Any support planned for NodeJS v14.x ?
As it is becoming the next LTS, we would like to jump to this version and skip updating from v10 to v12 .

**Comment by agracio** [comment]
New package is now published with Node.js 14.x support and a couple of important bug fixes https://github.com/agracio/edge-js/pull/95, https://github.com/agracio/edge-js/pull/101, https://github.com/agracio/edge-js/pull/102. Enjoy.
Thanks for everyone who worked hard to resolve problems and submit PRs.

**Comment by fforjan** [comment]
Awesome ! Thanks everyone who contributed to that !

**Comment by jdom** [comment]
Any plans of publishing to NuGet? The last release there is pretty old
