### ISSUE TITLE
Package size is getting huge, can it be streamlined?

### ISSUE THREAD

**Issue by dpolivy** [agracio/edge-js#108]
The package size for `edge-js` is starting to get quite large. Many of the older Node versions are no longer supported (e.g. any odd version number). Can they be pruned from the package to help keep the size down? Theoretically anything no longer in LTS support should also be pruned out and no longer supported.

Is there any other best practice for modules that distribute native modules to have it only pull down the required version for the platform being installed upon?

**Comment by agracio** [comment]
Good point, published new leaner package.
But its up to you what you want to package in your application. If you are distributing application for a specific NodeJs version or if you distributing for 32/64 bit only you can just delete unnecessary folder/s from `lib/native/win32` .

**Comment by dpolivy** [comment]
Thanks!

I'm not sure I agree about deleting unnecessary folders from inside the module -- that seems to be bad practice on a number of levels to go poking around in one of your dependent modules folders. Generally, when installing an app that depends on this, a CI build system will run `npm ci` or equivalent to install modules based on the package lockfile. It would be great if only the necessary dependencies were installed for runtime.

I know this is a bit of a change, but have you thought about using the [files](https://docs.npmjs.com/files/package.json#files) directive in `package.json` to filter out all of the source and test files that aren't needed to support runtime from the published module?

Anyone who wants to customize/build their own version can clone the repo and work with the source that way. Anyone who just wants to depend on it can then just reference the package, which only contains the files necessary to support the runtime.j It would also drastically clean up the contents of the published module to remove unnecessary items.

Going a step further, I wonder if it's possible to publish multiple versions of the module with major versions that correspond to the node version you're using. e.g. `edge-js@12` only runs on Node 12, `edge-js@14` only runs on v14, etc. Or, switching the module to use N-API instead of NAN so that it doesn't need to be rebuilt for each new major Node version. That's probably more work, but perhaps a better long term approach.
