### ISSUE TITLE
Does EdgeJs work with ASP.NET web application?

### ISSUE THREAD

**Issue by RaviTmg** [agracio/edge-js#109]
Edgejs works fine in a .NET console application. However, while running in ASP.NET web application (.NET Framework 4.5), I am getting following error: 

**System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'**

Am I missing something?

**Comment by agracio** [comment]
Issue fixed in https://github.com/agracio/edge-js/pull/119, please update to newest nuget package.
