### ISSUE TITLE
Can't use .net core when have Mono installed

### ISSUE THREAD

**Issue by playerx** [agracio/edge-js#110]
If there is a Mono installed on the machine `edge-js` tries to use it, even if `EDGE_USE_CORECLR=1` is set in the environment.

After removing Mono it uses .net core

**Comment by pmahend1** [comment]
Same here

**Comment by agracio** [comment]
Not sure what is the issue here, Mono tests used to run alongside .NET Core tests on Travis CI without an issue.
Right now Mono tests have been removed as it is no longer actively supported.
