### ISSUE TITLE
Load csx file from app.asar

### ISSUE THREAD

**Issue by MaxLiu0325** [agracio/edge-js#12]
can't not find path resources\app.asar\src\app\cs-script\test.csx

**Comment by agracio** [comment]
I havent used asar archives in my Electron apps myself, by my understanding is that you would not need to specify /app.asar/ in the path as Electron would allow you direct access to files in asar archive.

**Comment by agracio** [comment]
Looks like I am completely wrong here and according to the [guide](https://electron.atom.io/docs/tutorial/application-packaging/) you do need to include /app.asar/ in your path. Not sure why it fails in that case, will look into this further once I looked into other blocking items. Might take a couple of weeks. If you can create example Electron project with a failing code that would be helpful.
