### ISSUE TITLE
node.exe fails to download with download.js because nodejs.org no longer supports http:// (https required)

### ISSUE THREAD

**Issue by alan-copeland-keysight** [agracio/edge-js#122]
It appears that nodejs.org only allows secure downloads now. The download.js file (download of node.exe) fails with 301 (redirect errors).

**Comment by agracio** [comment]
Use earlier https://github.com/agracio/edge-js/pull/120 instead of yours, issue is now solved.

**Comment by alan-copeland-keysight** [comment]
Cool. Any idea when you'll have the next release @agracio ?

**Comment by agracio** [comment]
New version with support for 15.5.0 is released.
