### ISSUE TITLE
Object Reference

### ISSUE THREAD

**Issue by splitice** [agracio/edge-js#124]
I'm investigating edge-js for use in an existing project and was wondering if anyone had come across a similar problem and had a solution (other than the obvious dictionary mapping).

I would like to return an object reference from C# (called by Node) that can be used in calls to C# methods but does not need to be fully serialized and deserialized when crossing boundies. A unique object reference.

Of course I've thought about a dictionary, list or array of objects and returning the idx but I was wondering if anyone had a neater solution.

**Comment by agracio** [comment]
When you use edge your objects are converted from CLR (.NET) and V8 (Node) types and back, you would not be able to maintain a reference to an object.

**Comment by splitice** [comment]
Unforutnately my research into .net reference options tends to agree. array / dictionary are the primary options. It looks like however that array offset is very performant. That might be what I use.

Thanks anyway @agracio
