### ISSUE TITLE
Error: The edge module has not been pre-compiled for node.js version v15.5.0. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.

### ISSUE THREAD

**Issue by Kreijstal** [agracio/edge-js#125]
Okay, but what if I don't have Administrative rights effectively preventing me from installing Building tools, does that mean that this application... just won't work out of the box and I should look for alternatives? :(
I'm in windows 10 64bit, btw

**Comment by agracio** [comment]
Support for 15.5.0 was just released. But if you need to compile it for a version that is not supported you need all the listed prerequisites that cannot be installed without admin rights.
