### ISSUE TITLE
edge-cs is outdated and cannot be build with .net 5 ?

### ISSUE THREAD

**Issue by fforjan** [agracio/edge-js#129]
edge-cs relies on the project.json to restore the package and this cannot be build with .net 5.0 as the project.json format is not supported anymore.

See https://github.com/tjanczuk/edge-cs/blob/master/lib/bootstrap/project.json

**Comment by fforjan** [comment]
it means for us we have error in our continuous integration:
![image](https://user-images.githubusercontent.com/601810/108535636-66c55e80-7290-11eb-95cc-854487166e4b.png)]

**Comment by aboucher000** [comment]
Are there any plans to upgrade the package to .net core 5.0 / 6.0 ?
I could try to do it myself, but I have no experience in writing packages (for now).
As our projects are now targeting .net 6.0 and we cannot go backwards, we have no means of realizing a requested feature (call JS from C# and C# from JS).
Does anybody know an alternate package or way to do the same thing ?
