### ISSUE TITLE
On npm install edge-js loops through all nuget feeds in the config

### ISSUE THREAD

**Issue by ZlatkoAtanasov** [agracio/edge-js#13]
Hello there! In my project directory I have a _nuget.config_ that holds a private nuget feed and the official _nuget.org_ one. The problem is that _edge-js_ seems to loop through all feeds from the _nuget.config_ when it tries to restore its packages (on npm install) but it stumbles on the private feed, cannot access it and fails. I don't see any reason for _edge-js_ to try to access any other nuget feed except the official one.

**Comment by agracio** [comment]
This is expected behaviour for any .NET project, it will pick up nuget configuration from _nuget.config_ present in the project.

**Comment by ZlatkoAtanasov** [comment]
Yes, that is the purpose of the config being there but why should the edge-js module want to access all the feeds as it only needs to restore packages from nuget.org one? This issue will occur in every project trying to run the edge-js module with a nuget.config having a private feed. Isn't it appropriate to have a constraint in the edge-js module that calls only nuget.org feed since all the nuget packages it need are there?

PS: The problem does not occur on the [original edge module](https://github.com/tjanczuk/edge).

**Comment by agracio** [comment]
I am assuming that you are using .NET Core implementation.
The change is likely to do with `edge-js` support for .NET Core v.1x - 2.x while original project only supports .Net Core v1.0. To me it sounds like a correct behaviour and is likely a fix on .NET Core team part. Since it is running a standard `dotnet restore` command, it makes sense that it would use standard _nuget.config_ settings.

**Comment by ZlatkoAtanasov** [comment]
Sorry for the inconvenience but I am having this problem on a NodeJS project. The problem is that the project itself can authenticate and restore all needed packages but the edge-js module sees a nuget.config in the project's directory and tries to restore its packages from it also and when not authenticated it fails.

As far as I understand there is no custom implementation in the edge-js module that restores packages besides a standard cli ones. And if yes then why would everything work properly on the original edge module and won't work on this. It seems some of the new changes in the implementation did this side effect.
