### ISSUE TITLE
require(edgeNative) does not return

### ISSUE THREAD

**Issue by hahoyer** [agracio/edge-js#139]
When executing ...\node_modules\edge-js\lib\edge.js is comes to the line: 

`edge = require(edgeNative);`

It does not return.
The value of edgeNative is "...\\node_modules\\edge-js\\lib\\native\\win32\\x64\\14.17.4\\edge_nativeclr".
It looks like the edge_nativeclr cannot self register.

**Comment by jsykesdev** [comment]
for me, it returns {}
