### ISSUE TITLE
Question: How can I use edge-js in .net standard to call js functions

### ISSUE THREAD

**Issue by JiaHenry** [agracio/edge-js#145]
Hello,
I can't find any .net standard related sample which call JS functions in C#. The one in quick start is JS call .Net items.
I checked that the dll for .Net 4.5 provided with EdgeJs.Edge.Func but for .net standard total different it. So I want to know how / may I use it in .net standard.

Sorry for  disturb，

Thank you for advance,

Henry

**Comment by agracio** [comment]
Only framework 4.5 is supported when calling JS from .NET. Unfortunately documentation is outdated, there is no planned support for JS-> .net standard calls.
