### ISSUE TITLE
Request new release to support Node. version 16.x

### ISSUE THREAD

**Issue by danpodlogar** [agracio/edge-js#147]
Is there a possibility to get a new release created from master that supports Node version 16.x. I would like to use this library but we require an official release version.

Thank you

**Comment by danpodlogar** [comment]
Hello, was hoping to get a comment on this, is this possible to get a new release pushed out?

**Comment by ruaumoko** [comment]
Edge-JS 16.6.0?  I have it working with Node 16.13.2.

**Comment by danpodlogar** [comment]
All, we are looking to see when you will post the next 16.6.0 as an official release in Github? NPM shows next available release is 16.6.0 but when going here it shows a much older version as latest RELEASE version.  When will that happen?

**Comment by agracio** [comment]
Released
