### ISSUE TITLE
Cannot find module: edge_nativeclr

### ISSUE THREAD

**Issue by harunrst** [agracio/edge-js#164]
Hey there, I have been trying to run this library on my webpack build typescript-node project. But I am getting this error for a while, I checked all other issues related to this but there is no specific solution. May I have some guidance here?

![image](https://user-images.githubusercontent.com/26141403/202181389-75503ad3-baaf-4fef-b541-b8ba45b1ff5a.png)

**Comment by agracio** [comment]
Please take a look at webpack packaging examples here: https://github.com/agracio/electron-edge-js/issues/39
You need to specify `edge-js` as external package similar to the code below:
...
  externals: {
    'edge-js': 'commonjs2 edge-js',
  },
  node: {
    __dirname: true,
    __filename: true,
  },
...

**Comment by harunrst** [comment]
thanks for the rapid response! it resolved my issue :)
