### ISSUE TITLE
Old version(5.0.5) is shown in performance/BookService/packages.config for Newtonsoft.json

### ISSUE THREAD

**Issue by vinodkumarsharma276** [agracio/edge-js#167]
Our project is consuming edge-js@18.4.2 which is the latest available package but our security system says that we are somehow referring Newtonsoft.json's v5.0.5 and need to mention 13.0.1. After digging deeper we found that its coming from  _**performance/BookService/packages.config**_ but the Github source of edge-js has its version as 18.4.2 and Newtonsoft.json version as 13.0.1 in  performance/BookService/packages.config.

_So, our wild guess is that if edge-js is published to npm with 18.4.3 we will be able to get the updated file -->  performance/BookService/packages.config with Newtonsoft.json's package mentioned as 13.0.1._

Can someone take a look at this and publish the latest version to npm.
@agracio @corylulu @shferguson-truefit

**Comment by agracio** [comment]
Released
