### ISSUE TITLE
Node 18.13.0 and Edge 16.6.0 or 19.13.0

### ISSUE THREAD

**Issue by tgf-coder** [agracio/edge-js#174]
I have a project that is being updated from node 16.17 to 18.13 and this is  causing edge-js to break with the precompile error. I have tried running build.bat for node 18.13 but with no success. I am wondering what the cleanest way to solve this is as well as what the issue might be.

**Comment by jkl3848** [comment]
edge-js wasnt able to build for me on Mac while I was on Node 19. I used nvm to use Node 14 in order to build and run successfully. I haven't tested all the limitations but it seems to have some issues with newer versions of Node.
