### ISSUE TITLE
Does this library still support running JS inside  .Net ?

### ISSUE THREAD

**Issue by nikhil-archerirm** [agracio/edge-js#176]
Previously EdgeJS used to provide us a Nuget package, with a node.dll, which could be included in a .Net project.
That seems to have stopped now. 

The documentation mentions that we can create a nuget package ourselves but those steps are not hardened and did not work for me.

@agracio So, is the use-case of running JS inside .Net code no more supported ??

**Comment by nikhil-archerirm** [comment]
I am currently using v11.3.3 of the Nuget package published. https://www.nuget.org/packages/EdgeJs/11.3.3

I have tried replacing the content folder in this older nuget package with the newer files obtained via the newer npm package.
I saw that the new npm package for edgeJS doesn't provide the node.dll anymore so I created a node.dll for node v18 myself and included that too in the nuget package. But I keep getting this error when the control goes to edgeJS.

![Screenshot 2023-01-16 at 4 12 44 PM](https://user-images.githubusercontent.com/114147673/218571952-ade09893-5a45-404e-984c-7b8105038345.png)

**Comment by agracio** [comment]
New package published https://www.nuget.org/packages/EdgeJs/20.12.3

**Comment by nikhil-archerirm** [comment]
Thanks a ton!!
I will checkout the new package.

**Comment by nikhil-archerirm** [comment]
The Nuget package does work but seems like it isn't signed.
I will create a new issue to track this signing issue.

**Comment by agracio** [comment]
I do not believe the package was ever published as signed.

**Comment by nikhil-archerirm** [comment]
Sorry for the delayed response.

The error says that the package is signed but not from a trusted signer.
So, the package seems to be signed but it appears that the signer isn't trusted by nuget.org.
I have created a new issue with more details about it.
https://github.com/agracio/edge-js/issues/216
