### ISSUE TITLE
CORECLR_DIR mentioned in README is unused

### ISSUE THREAD

**Issue by SlyryD** [agracio/edge-js#177]
`CORECLR_DIR` mentioned in README does not exist in code. Did this get replaced with `EDGE_APP_ROOT` for finding coreclr.dll? `CORECLR_VERSION` still exists.

**Comment by agracio** [comment]
Looks like it but I don't really want to modify original README for `edge`, pretty sure there are many items that are out of date. Feel free to submit PR if it really bothers you.
