### ISSUE TITLE
Node.js v20 support

### ISSUE THREAD

**Issue by rvalimaki** [agracio/edge-js#181]
Node version 20 isn't supported yet. I was able to compile edge-js on x64 Windows 10 & node.js v 20.2.0. Also I did ran through all the mocha tests, 73 passing, only 1 failing:

  73 passing (9s)
  1 failing

  1) .net returns Func to node.js
       [.NET] releases the func:
     AssertionError [ERR_ASSERTION]: This test must be run with --expose-gc set
      at Context.<anonymous> (test\103_net2node.js:260:10)
      at process.processImmediate (node:internal/timers:478:21)
      
 Also I can run the edge-js without problems, altough all I do is just call one .NET call and get the result alright.

**Comment by PranKe01** [comment]
+1

Please update the versionMap variable in edge.js file, to support node v20 (and v21 in end of october).

**Comment by x4080** [comment]
@PranKe01 just changing the verionMap variable will make it work for node v20 and even v21 ?

**Comment by PranKe01** [comment]
> @PranKe01 just changing the verionMap variable will make it work for node v20 and even v21 ?

Yes (:

**Comment by x4080** [comment]
@PranKe01 Thanks

**Comment by Venryx** [comment]
I've tried editing `versionMap` variable, like so:
```
var versionMap = [
    [ /^14\./, '14.19.3' ],
    [ /^16\./, '16.15.1' ],
    [ /^18\./, '18.4.0' ],
    [ /^19\./, '19.3.0' ],
    [ /^20\./, '19.3.0' ],      // <-- I added this line
];
```

However, when trying to run, I get this error:
```
Signal: uncaughtException Error: Error: Module did not self-register: '\\?\C:\PATH_TO_MY_PROJECT\node_modules\edge-js\lib\native\win32\x64\19.3.0\edge_nativeclr.node'.
```

Any tips?

**Comment by x4080** [comment]
@Venryx Could you share the node-gyp build files ?

Thanks

**Comment by Venryx** [comment]
> @Venryx Could you share the node-gyp build files ?
> 
> Thanks

Do you mean the resulting ".node" files? If so, I've just uploaded them here: https://github.com/Venryx/edge-js/releases/tag/v20.5.0-win-debug

**Comment by x4080** [comment]
@Venryx thanks

**Comment by agracio** [comment]
Added support for Node v20.x, published

**Comment by x4080** [comment]
@agracio cool !
