### ISSUE TITLE
PowerShell Support?

### ISSUE THREAD

**Issue by engineertdog** [agracio/edge-js#190]
I see that `edge-ps` does still work, but is dated. I was wondering if this project picked up support for running PowerShell as well?

**Comment by agracio** [comment]
PowerShell support is in README

**Comment by engineertdog** [comment]
I originally thought there was an error or bug, but after posting the issue I was able to resolve the problem I had. I then changed the subject of this issue to curiosity around the support for `edge-js` and `edge-ps`.

**Comment by agracio** [comment]
`edge-ps` is not part of this project, if it stops working or needs major update then perhaps I could take a look or maybe a person with better PowerShell knowledge would publish an alternative.

**Comment by agracio** [comment]
There will be some minor updates to `edge-ps` package coming in the next couple of weeks one of them is adding support for dotnet 8. Otherwise there are no plans for any major changes unless there issues or proposals for improvements.
