### ISSUE TITLE
Nuget builds?

### ISSUE THREAD

**Issue by julesbro** [agracio/edge-js#2]
I didn't see a way to grab pre-built binaries for .Net projects.  I may just be overlooking the link, but if not would you consider publishing builds of this fork to a Nuget package?  You've put a lot of work into bug fixes and features that the original repo hasn't accepted, and I imagine a lot of other .Net developers relying on this would appreciate the option of being able to just pull install your fork rather than having to rebuild the packages each time.

**Comment by IntranetFactory** [comment]
It would even be better if the release would be available at https://github.com/agracio/edge-js/releases

**Comment by agracio** [comment]
This is a good point, I will start by adding compiled files to releases and will work on Nuget package later. Will releases files today/tomorrow.

**Comment by agracio** [comment]
Took some time, but latest 8.1.4 release has double edge binaries attached on release page

**Comment by davidhouweling** [comment]
@agracio any chance of getting nuget packages up?

**Comment by agracio** [comment]
For now binaries are available in https://github.com/agracio/edge-js/releases, will try to get nuget package released in the near future.

**Comment by agracio** [comment]
Took some time, but nuget package is finally done: https://www.nuget.org/packages/EdgeJs.
Let me know if there are any problems.

**Comment by IntranetFactory** [comment]
I've just downloaded https://github.com/agracio/edge-js/archive/v9.3.1.zip - but that seems to not contain node.dll  Is node.dll missing intentionally or do I miss something?

Next I downloaded https://www.nuget.org/api/v2/package/EdgeJs/9.3.2 It contains node.dll, but the file version is 8.9.3.0

I was looking to update to version 8.9.3 LTS - so is the node.dll from NuGet the correct one to use?

**Comment by agracio** [comment]
The archive you downloaded is just the source repo.
Since I published binaries to NuGet I stopped attaching them to release page. NuGet package that you downloaded is the correct one.  

I've reattached binaries to the release page as well.

**Comment by IntranetFactory** [comment]
Thank you for your fast reply. Would be great if binaries can be downloaded without being forced to use NuGet.

**Comment by agracio** [comment]
It's a good point, not everyone wants to go to NuGet, I have reattached binaries to 9.3.1 release page and will make sure to publish to both NuGet and release page in the future.
