### ISSUE TITLE
Don't include unused files in published npm package

### ISSUE THREAD

**Issue by bdukes** [agracio/edge-js#20]
It seems like we should be able to add an `.npmignore` file for a bunch of files in this package, which would (1) reduce the size of the package, and (2) stop Visual Studio Code from showing warnings about how the sample code is setup.

I'm thinking something like the following, let me know if you're interested in a PR:
```
.gitattributes
.jshintrc
Dockerfile
LICENSE
*.md
*.yml
*.ts
performance/
samples/
src/
stress/
test/
tools/
```

Does that sound right?

**Comment by agracio** [comment]
I prefer to include all files in package and to keep it inline with original `edge` repo. VS Code should not show warning for any modules in _node_modules_ directory, what kind of warning you getting?

**Comment by bdukes** [comment]
I get a warning about `project.json` no longer being supported for .NET Core apps, and a bunch of "unresolved dependencies from 'node_modules\edge-js\js\src\...\project.json`" with an option to restore dependencies.

![example error messages](https://user-images.githubusercontent.com/59507/35527398-3bf31366-04f0-11e8-8304-a3523f985542.png)

**Comment by agracio** [comment]
That is a different problem. _project.json_ was a _.csproj_ replacement in .NET Core 1.0.0 and below and Microsoft went back to _.csproj_ files for .NET Core 1.0.1 and above. While `edge-js` does not actively support .NET Core 1.0.0 removing those files would make it incompatible and there are still some people especially in large companies that use it, I even had a request to keep it. 
I am afraid for now we are stuck with those VS Code warnings although I personally think this a bug in OmniSharp plugin for VS Code as it should not look at projects in _node_modules_ in the first place. I haven't checked but maybe there is an option to disable _node_modules_ lookup somewhere in options?

**Comment by D10221** [comment]
Hi, 
the following settings seem to do the tick for me.
I'm probably overdoing it with 2nd line .
```
// workspace settings:    ${workspaceFolder}/.vscode/settings.json
 ""csharp.suppressProjectJsonWarning": true,
    "omnisharp.autoStart": false,
```
