### ISSUE TITLE
is it support dotnet core 2.0 ? 

### ISSUE THREAD

**Issue by zhu1531** [agracio/edge-js#21]
can u show some samples about using dotnet core 2.0 on linux ?

**Comment by agracio** [comment]
Usage is exactly the same as .NET Framework but you need to set `EDGE_USE_CORECLR=1` Node.js variable before running the code.

**Comment by zhu1531** [comment]
`EDGE_USE_CORECLR=1` is not work.

and i see that today:    
"quick start" app for .NET Core here: https://github.com/agracio/edge-js-quick-start.Works fine when building dlls using .NET Core 2.0.

**Comment by agracio** [comment]
`edge-js-quick-start` uses `EDGE_USE_CORECLR=1` to work...

**Comment by zhu1531** [comment]
。。。
