### ISSUE TITLE
Is it possible to run a .NET function from the main Node.js thread? 

### ISSUE THREAD

**Issue by garciadelcastillo** [agracio/edge-js#214]
Howdy! 

And congrats for the project and thank you for maintaining it! 

I am trying to call a .NET function from a dll that requires it to be ran on the main thread (reason is that it uses OpenGL and context rendering under the hood). Code looks roughly like this:

```js
process.env.EDGE_USE_CORECLR = 1
const edge = require('edge-js');

const dll_path = './OpenGL-based-routines.dll'

const RenderTriangle = edge.func({
  assemblyFile: dll_path,
  typeName: 'Library.Core',
  methodName: 'RenderTriangle',
  sync: true
});

const triangleParams = {...};

const pixels = RenderTriangle(triangleParams, true);
console.log(pixels);
```

And the C# method looks like this:
```csharp
public async Task<object> RenderTriangle(dynamic input)
{
    var pixels = Renderer.Triangle(inputs);  // this function uses OpenGL/GLFW
    return new { pixels };
}
```

And I get the error:

    GLFW can only be called from the main thread!

Is there any way to use Edge-js in a way that the function gets called from the main thread, perhaps avoiding the `Task` API? 

Thank you!

**Comment by agracio** [comment]
Hi,
edge-js can only run `Task` methods in C#, quick search returns this suggestion from StackOverflow:

```cs
Task t = new Task(() =>
{
    ...
});
t.Start(TaskScheduler.FromCurrentSynchronizationContext());
```

**Comment by garciadelcastillo** [comment]
Thanks for the suggestion @agracio! 

Spent the day yesterday trying versions of your suggestion, but couldn't quite figure out how to retrieve the `main` thread. The issue is that, in order to do it, some part of the C# code needs to be ran synchronously from the same thread that is running everything else, i.e. the Nodejs main thread, in order to be able to capture a reference to the `SynchronizationContext`, and then use it inside the task the way you suggested above. But since `edge-js` only fires `Tasks`, I can't figure out a way to do so from within a Task, which is by definition running on a different thread...

There is [a section in the README](https://github.com/agracio/edge-js?tab=readme-ov-file#to-sync-or-to-async-that-is-the-question) where you describe how to run a Python script on the _singleton V8 thread_. It does sound like that's what I am trying to do, but for a .NET external dll. Do you think that could be possible? 

Thanks!

**Comment by agracio** [comment]
There is a better explanation here: [Sync Execution](https://github.com/agracio/edge-js?tab=readme-ov-file#executing-synchronously-without-function-callback), as you can see it still uses `Task<object>`.

Let me try to create a quick example of I think the issue could be resolved using the 'EDIT' part of my comment.

**Comment by garciadelcastillo** [comment]
Absolutely, let me write a quick one and share here.

**Comment by agracio** [comment]
I am adding my implementation to quick start now

**Comment by garciadelcastillo** [comment]
Here you go: https://github.com/garciadelcastillo/edgejs-opengl

If you run the main script in the root, it should give you the non-main-thread error...

**Comment by agracio** [comment]
Thanks I will take a look at a look at it in a few hours

**Comment by agracio** [comment]
I am busier than originally expected so will have to wait till after the weekend.

**Comment by agracio** [comment]
I am not sure if it is possible but if instead of relying on resources `GLFW.Init()` can be called directly there maybe a solution.

Just a personal opinion but it also appears to be a deficiency of GLFW, most other UI centric framework a have specific implementations that allows to propagate a call directly to main thread for example `Dispatcher` in WPF and `Device` in now discontinued Xamarin Forms and from memory many others.

**Comment by agracio** [comment]
After some digging around and experimenting with the code some more this it appears to be a specific edge-js issue. 
As you pointed out in your earlier comment in this particular case 'main thread' refers to the  main Node.js thread and not C# executing thread. I do not see how this can be resolved.

**Comment by agracio** [comment]
Removed all my previous comments it appears there is something else involved that needs to be investigated.

**Comment by agracio** [comment]
Unfortunately it looks like there is just no way to support GLFW using edge-js.

**Comment by garciadelcastillo** [comment]
Oh no! Well, thanks for trying anyway @agracio :)
