### ISSUE TITLE
Exception when used in extension

### ISSUE THREAD

**Issue by hahoyer** [agracio/edge-js#215]
Created an ts-extension with "yo code".
Then I included edge-js and added some dummy usage to ensure that it got not optimized.

```
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';
import * as edge from 'edge-js';

if (edge === null) {console.log('no edge');};

...
```

When I start the extension and called the command I get the following error:

```
Activating extension 'undefined_publisher.ts-test' failed: Module did not self-register: '\\?\d:\data\develop\js\Reni.VSCode\ts-test\node_modules\edge-js\lib\native\win32\x64\20\edge_nativeclr.node'..
```

```
My system: 
Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045


```

[package.json](https://github.com/user-attachments/files/16672368/package.json)
[tsconfig.json](https://github.com/user-attachments/files/16672369/tsconfig.json)
[extension.ts](https://github.com/user-attachments/files/16672432/extension.ts.txt)

**Comment by agracio** [comment]
For VSCode you need to use https://github.com/agracio/electron-edge-js

**Comment by agracio** [comment]
Be careful to pick the correct version of `electron-edge-js` to match VSCode version. 
Electron started updating Node.js version constantly starting with version 30 forcing me to recompile binaries every time Node.js is updated. Look at the table for Electron/Node.js version to find the right one.
