### ISSUE TITLE
Nuget package v20.12.3 throws "This package is signed but not by a trusted signer." error.

### ISSUE THREAD

**Issue by nikhil-archerirm** [agracio/edge-js#216]
I have my Nuget config configured to trust signed packages from Nuget.org
![NugetConfig](https://github.com/user-attachments/assets/7e12fe20-224d-4a6c-bfe5-f4dfba823bda)

The older versions of EdgeJS gets installed correctly with this Nuget configuration.
![edgeJS v11 3 3](https://github.com/user-attachments/assets/015e01c0-efd5-4573-a92c-6c1055962380)

But the version v20.12.3 throws the error "This package is signed but not by a trusted signer." when I try to install it or upgrade to it.
![edgeJS v20 12 3](https://github.com/user-attachments/assets/e7826158-d6ac-4b76-b259-6d9797d5d675)

**Comment by agracio** [comment]
Unfortunately there is not much that I can do here.  The package is not signed and never was, you can download both packages as .nupkg and compare.
Maybe there is some kind of change on Nuget part where it assigns a signature to newly uploaded packages now?

**Comment by agracio** [comment]
Does this resolve the issue?
