### ISSUE TITLE
Attempted to build for Node 22.7 but unsure how to proceed.

### ISSUE THREAD

**Issue by connor-ricks** [agracio/edge-js#217]
Hello, I was trying to build this locally to work with Node.JS 22.7.0 on windows. I followed the building instruction in the readme, but I'm unsure how to proceed once I've ran the commands.

```
cd tools
build.bat release 22.7.0
```

**Comment by connor-ricks** [comment]
Ideally I would just use [`v22.1.2`](https://github.com/agracio/edge-js/releases/tag/v22.1.2) that you have published, but when attempting to use it in my project it's unhappy with my local installed versions.

Does the package not work with all minor versions or is it tied to a specific version for each release you have?

**Comment by agracio** [comment]
Could you explain what issues you have in your local project, post errors etc.
Edge.js works with any minor version of major release so should work with 22.7.0

**Comment by connor-ricks** [comment]
Thanks for the quick response!

I uploaded a blank template project with Next.JS [here](https://github.com/connor-ricks/edge-js-debug).

It has a single route you can hit by calling `localhost:3000/api` when running with `npm run dev`

I get the attached error when attempting to import edge-js.

![edge](https://github.com/user-attachments/assets/197294ba-1f12-4ed8-ace5-24f8e0b6041a)

**Comment by agracio** [comment]
I am unable to access the project you linked. Are you sure you running the correct version of Edge.js?

**Comment by connor-ricks** [comment]
Wooops sorry! I made it public now. I'm using 22.1.2 in the project.

**Comment by agracio** [comment]
I see the problem now, this is not an issue with Edge.js but rather Next.js creating its own packages and sources using internal 'webpack'. 
In the console the error originates from `edge-js-debug\.next\server\vendor-chunks\edge-js.js:19` which is not an appropriate place for edge.js file. 
I am not familiar with Next.js but there should be a setting where you can exclude certain modules from webpack. 
You need to do something similar to [Node.js Application Packaging](https://github.com/agracio/edge-js?tab=readme-ov-file#nodejs-application-packaging) but for Next.js.
Easiest way to verify that Edge.js does work with Node.js v22.7.0 is to run https://github.com/agracio/edge-js-quick-start

**Comment by connor-ricks** [comment]
Thanks for pointing me in the right direction @agracio! I know very little about Webpack and I'm fairly new to Node/React. I'm primarily an iOS engineer.

For anyone else trying to fix this....

I had to add 

```
  experimental: {
    serverComponentsExternalPackages: ['edge-js'],
  },
```

to my `next.config.mjs`

**Comment by agracio** [comment]
Updated README to include Next.js example
