### ISSUE TITLE
System.Runtime not found

### ISSUE THREAD

**Issue by hahoyer** [agracio/edge-js#221]
When edge (electron-edge-js 30.1.2) tries to open my DLL it get an error: 

`Activating extension 'ixu.reni-vscode' failed: Die Datei oder Assembly "System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden..
`
(Sorry for the German. Don't know how to change this without changing everything.
Translation: The file or assembly "System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or a dependency of it could not be found. The system cannot find the specified file.)

I use this DLL also in another situation (Visual-Studio project) and it turned out to work fine.

My vscode: 
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by agracio** [comment]
Usually this error indicates that you are running using .NET Framework rather than .NET Core. Did you set `process.env.EDGE_USE_CORECLR = 1;` in your Electron project? 
Take a look at https://github.com/agracio/electron-edge-js-quick-start for reference on setting up `electron-edge-js` project.

**Comment by hahoyer** [comment]
The quick-start is working,  but I have no idea how to apply this to my project. 
Probably you can have a look at my extension. It is quite short.


```
const path = require("path");

const dllPath = "a:/develop/Reni/dev/out/Debug/net8.0/publish";
const name = "ReniLSP";
const fullName = path.join(dllPath, name + ".dll");

//process.env.EDGE_USE_CORECLR = 1;
//process.env.EDGE_APP_ROOT = dllPath;

var edge = require("electron-edge-js");

function activate(context) {
  const server = edge.func(fullName);
  const fff = 3
}

// This method is called when your extension is deactivated
function deactivate() {}

module.exports = {
  activate,
  deactivate,
};

```

When I comment out the two environment settings I get another error: 

`Activating extension 'ixu.reni-vscode' failed: edge.initializeClrFunc is not a function.`

**Comment by agracio** [comment]
With `process.env.EDGE_USE_CORECLR = 1;` you getting `System.Runtime, Version=8.0.0.0` exception?

**Comment by hahoyer** [comment]
I guess it is .Net-Core. In msbuild I use this setting: 

`<TargetFramework>net8.0</TargetFramework>`

**Comment by agracio** [comment]
That means its .NET Core so everything should be working fine. If you can create a repo to reproduce the issue i can take a look.

**Comment by hahoyer** [comment]
You can try my project. it is public.
https://github.com/hahoyer/reni.cs
checkout master,
with visual studio open __root__/src/reni2.sln and compile ReniLSP as debug
The result will be in __root__/out/Debug/net8.0
The vscode project is __root__/src/Reni.VSCode/reni-vscode
I apologise for the awkward situation. I was not prepared for it.

**Comment by hahoyer** [comment]
Ah, the extension is triggered when you open any file with extension reni.  see __root__/src/renisource

**Comment by hahoyer** [comment]
I created the branch [reproduce/edge-js](https://github.com/hahoyer/reni.cs/tree/reproduce/edge-js) where everything is reduced to the minimum.

**Comment by agracio** [comment]
You are not setting up `edge-js` or `electron-edge-js` correctly. Given your full project at master if I copy your dlls with all the dependencies to quick-start bin folder (converted to dotnet 8.0) project runs with following changes:

`app.js`
```js

// code before this line is unchanged

const reni2dll = path.join(baseNetAppPath, "ReniLSP.dll");

var reni2 = edge.func({
    assemblyFile: reni2dll,
    typeName: 'ReniLSP.Startup',
    methodName: 'Invoke'
});

exports.run = function (window) {

    reni2('', function(error, result) {
        if (error) throw error;
        window.webContents.send("fromMain", 'getItem', JSON.stringify( result, null, 2 ));
    });
    
    return;
}
```

Result:

```js
{
  "Result": {},
  "Id": 1,
  "Exception": null,
  "Status": "RanToCompletion",
  "IsCanceled": false,
  "IsCompleted": true,
  "IsCompletedSuccessfully": true,
  "CreationOptions": "None",
  "AsyncState": null,
  "IsFaulted": false
}
```

Project files copied:
```
  ReniUI.dll
  ReniLSP.dll
  ReniExe.dll
  Reni.dll
  OmniSharp.Extensions.LanguageServer.Shared.dll
  OmniSharp.Extensions.LanguageServer.dll
  OmniSharp.Extensions.LanguageProtocol.dll
  OmniSharp.Extensions.JsonRpc.dll
  Nerdbank.Streams.dll
  Microsoft.VisualStudio.Validation.dll
  Microsoft.VisualStudio.Threading.dll
  Microsoft.VisualStudio.TextTemplating.Interfaces.11.0.dll
  Microsoft.VisualStudio.TextTemplating.Interfaces.10.0.dll
  Microsoft.Extensions.Primitives.dll
  Microsoft.Extensions.Options.dll
  Microsoft.Extensions.Options.ConfigurationExtensions.dll
  Microsoft.Extensions.Logging.dll
  Microsoft.Extensions.Logging.Abstractions.dll
  Microsoft.Extensions.DependencyInjection.dll
  Microsoft.Extensions.DependencyInjection.Abstractions.dll
  Microsoft.Extensions.Configuration.dll
  Microsoft.Extensions.Configuration.Binder.dll
  Microsoft.Extensions.Configuration.Abstractions.dll
  Microsoft.CodeAnalysis.dll
  Microsoft.CodeAnalysis.CSharp.dll
  Microsoft.Bcl.AsyncInterfaces.dll
  MediatR.dll
```

**Comment by hahoyer** [comment]
I changed app.js like this: 

```
const { ipcMain} = require("electron");
const path = require('path');
var namespace = 'QuickStart.Core';
var version = '8.0'

const baseNetAppPath = path.join(__dirname, '/src/'+ namespace +'/bin/Debug/net' + version);

process.env.EDGE_USE_CORECLR = 1;
process.env.EDGE_APP_ROOT = baseNetAppPath;

var edge = require('electron-edge-js');

const reni2dll = path.join(baseNetAppPath, "ReniLSP.dll");

var reni2 = edge.func({
    assemblyFile: reni2dll,
    typeName: 'ReniLSP.Startup',
    methodName: 'Invoke'
});

exports.run = function (window) {

    reni2('', function(error, result) {
        if (error) throw error;
        window.webContents.send("fromMain", 'getItem', JSON.stringify( result, null, 2 ));
    });

    return;
}
```

Also I copied all files according to your list.

Then I get: 

```
$ npm start

> electron-edge-js-quick-start@1.0.0 start
> electron --core .


App threw an error during load
Error: Call to coreclr_create_delegate() for G failed with a return code of 0x80070002.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2559)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (A:\develop\Training\electron-edge-js-quick-start\node_modules\electron-edge-js\lib\edge.js:52:12)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
```

**Comment by hahoyer** [comment]
In the meantime I have found out that it works if I comment out the following line:

```
process.env.EDGE_APP_ROOT = baseNetAppPath;
```

But I don't understand it. It's "fishing in the dark".

It only helps in the Quickstart project. It doesn't help where I need it. This is an extension. Apparently something is slightly different again.

**Comment by agracio** [comment]
This is strange as it worked for me the way I posted.

**Comment by hahoyer** [comment]
I'm currently trying to approximate your project to mine step by step. Let's see if I can find the place where it breaks.

**Comment by agracio** [comment]
I think we should first get to the core of the issue with `process.env.EDGE_APP_ROOT = baseNetAppPath;` if it works for me in quick-start but not for you then something is off here.

**Comment by hahoyer** [comment]
My vscode project is also included. If you would like to have a look...
Copied everything.

**Comment by agracio** [comment]
I do not know much about VSCode extensions tbh.

**Comment by hahoyer** [comment]
There is also a launch-config with just an app.js
This also does not work.

**Comment by hahoyer** [comment]
This is so strange. 
I deleted my working copy. Copied your project over mine. Tested and reverted step by step to my version. Now it works!
Must be some caching problem.

**Comment by hahoyer** [comment]
My extension is also working now. 
Fun fact: For the extension to run the `process.env.EDGE_USE_CORECLR = 1;` is required. For just running it as app.js not.

**Comment by agracio** [comment]
This is means that the console that you are running has `EDGE_USE_CORECLR=1` set as env variable and if you open it in new console it would break.

**Comment by hahoyer** [comment]
Ah ok.
So since it works now I guess we can close this issue. Thank you very much for your help.
