### ISSUE TITLE
C# DLL imported anonymous functions always returning undefined

### ISSUE THREAD

**Issue by ansaria11** [agracio/edge-js#223]
To communicate between my JS and C# backend I have created an interface class, which I compiled into a DLL. I initially exported each function individually from the DLL using edge.js:
C#:
```
 public async Task<object> InvokeCreateModel(dynamic input)
 {
     switch (input)
     {
         case "Cube":
             return Manager.CreateModel(Shapes.Cube);
         default:
             return "Error: Invalid Shape";
     }
 }
```
main.js:
```
async function GetModel(index) {
    const InvokeGetModel = edge.func({
      assemblyFile: join(__dirname, "../../resources/dlls/backend.dll"),
      typeName: "backend.src.Interface",
      methodName: "InvokeSendModel"
    })
    const result = await new Promise((resolve, reject) => {
      InvokeGetModel(index, (error, result) => {
        if (error) reject(error);
        else {
          resolve(result)
        }
      })
    })
    return result
  }
```
However I could not preserve data between function calls as a new Interface object is initialised whenever I load from the DLL. To prevent this, I took inspiration from [sample 110](https://github.com/agracio/edge-js/blob/master/samples/110_clr_instance.js) and created this class:
C#
```
namespace backend.src
{
    public class Interface
    {
        public Interface()
        {

        }
        public async Task<object> CreateInterface(dynamic input)
        {
            Manager manager = new Manager();
            return new
            {
                InvokeSendModel = (Func<object, Task<object>>)(
                    async (index) =>
                    {
                        return await Task.Run(() => manager.SendModel((int)index));
                    }
                ),
                InvokeCreateModel = (Func<object, Task<object>>)(
                    async (shape) =>
                    {
                        switch ((string)shape)
                        {
                            case "Cube":
                                return manager.CreateModel(Shapes.Cube);
                            default:
                                return "Error: Invalid Shape";
                        }
                    }
                ),

            };
        }
    }
}
```
However, when called in `main.js`, the functions behave as expected (checked using console logs) but they always return undefined.
JS
```
async function CreateInterface() {
    const CreateEdgeInterface = edge.func({
      assemblyFile: join(__dirname, "../../resources/dlls/backend.dll"),
      typeName: "backend.src.Interface",
      methodName: "CreateInterface"
    })
    const result = await new Promise((resolve, reject) => {
      CreateEdgeInterface(null, (error, result) => {
        if (error) reject(error);
        else {
          resolve(result)
        }
      })
    })
    return result
  }


  const backendInterface = CreateInterface()
  //Backend IPC
  ipcMain.handle("backend:getModel", async (event, index) => {
    try {
      const loadInterface = await backendInterface
      console.log(loadInterface.InvokeSendModel)
      const result = await loadInterface.InvokeSendModel(index)
      console.log("loaded: ", result)
      return result
    } catch (error) {
      console.log("Error communicating with backend: ", error)
      throw error
    }
  })

  ipcMain.handle("backend:createModel", async (event, shape) => {
    try {
      const loadInterface = await backendInterface
      const result = await loadInterface.InvokeCreateModel(shape)
      return result
    } catch (error) {
      console.log("Error communicating with backend: ", error)
      throw error
    }
  })
```

Is my implementation wrong, or is what im trying to do not possible in edge-js? If it is possible, how do I implement this?
Many Thanks.

**Comment by agracio** [comment]
Have you tried recreating https://github.com/agracio/edge-js/blob/master/samples/110_clr_instance.js in a simple project, for example adding it to `edge-js-quickstart` or `electron-edge-js-quickstart` and then modifying code until it starts working for your project?

**Comment by ansaria11** [comment]
I referenced it but I believe that it works differently when compiling my C# into an assembly. You can see from my code that its almost exactly the same in my C#, but I'm getting different outputs.

**Comment by agracio** [comment]
Maybe you need to have a small inline code part that references an object in your assembly so that way you will retain a handle on it, not sure but worth a try.

**Comment by ansaria11** [comment]
Solution:
Must input true as the last param when calling anonymous functions

`const result = await loadInterface.InvokeSendModel(index)`

becomes

`const result = await loadInterface.InvokeSendModel(index, true)`

not sure why but it fixes it 👍

**Comment by agracio** [comment]
Adding `true` at the end means you are executing your method synchronously, take a quick look at this part of readme so you don't run into unexpected problems with this approach [Executing synchronously without function callback](https://github.com/agracio/edge-js#executing-synchronously-without-function-callback)
