### ISSUE TITLE
Using edge-js with .NET Core 7 without .NET SDK?

### ISSUE THREAD

**Issue by BeneRasche** [agracio/edge-js#226]
Is it possible to use edge-js without a .NET SDK while targeting a .NET Core DLL?

Using the [quick-start example](https://github.com/agracio/edge-js-quick-start), it is not possible to run the code with "npm start" while not having a .NET SDK installed on the system.

The documentation seems outdated. For example, it says to 

> target the netcoreapp2.x or netstandard2.0 framework moniker.

What changes are required to make the example run with .NET Core 7 using only the .NET 7 Runtime?

It is easily reproduced by building with 

> dotnet build src/QuickStart.sln

and then either running it on a virtual maschine without the .NET SDK or temporarily uninstalling the .NET SDK

```
npm start

edge-js-quick-start@1.0.0 
start node main.js core

CoreClrEmbedding::Initialize - Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
### Application base path: C:\GIT\edge-js-quick-start\src\QuickStart.Core\bin\Debug\net7.0
### Application dll: C:\GIT\edge-js-quick-start\src\QuickStart.Core\bin\Debug\net7.0\QuickStart.Core.dll


C:\GIT\edge-js-quick-start\node_modules\edge-js\lib\edge.js:174
    return edge.initializeClrFunc(options);
                ^

TypeError: edge.initializeClrFunc is not a function
    at exports.func (C:\GIT\edge-js-quick-start\node_modules\edge-js\lib\edge.js:174:17)
    at Object.<anonymous> (C:\GIT\edge-js-quick-start\main.js:26:34)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.18.0
```

**Comment by agracio** [comment]
You need to use latest `edge-js` release v22.9.0 that addresses the issue of standalone .NET applications. 
However you also need to publish your .NET library first for quick-start use `dotnet publish src/QuickStart.sln --self-contained -r win-x64 -c Release` and then point your app to `src\QuickStart.Core\bin\Release\net8.0\win-x64\publish` or if you building for 7.0 then point to the correct directory.

**Comment by agracio** [comment]
quick-start updated to .NET 8.0 and latest Edge.js release.

**Comment by agracio** [comment]
There are some caveats to using standalone .NET library in Edge.js described here https://github.com/agracio/electron-edge-js-quick-start-forge/issues/1#issuecomment-2417479022

**Comment by agracio** [comment]
> So to be clear: Using edge-js without .NET SDK requires the .NET build to be published as self-contained?
> 
> If so, is there a specific reason for why that is?

Any .NET Core library deployed to environment without .NET Runtime has to be published. If you have .NET  Desktop Runtime installed without SDK then you do not need to publish.

**Comment by BeneRasche** [comment]
I was probably a bit unclear (only mentioned it once in the middle) that for my production setting, the customers have a .NET runtime installed on their system as a prerequisite.

Yet, the initial error stays. What changed are required to make the example project run only with the .NET runtime? (But not as a published standalone app)

```
node main.js core

CoreClrEmbedding::Initialize - Could not resolve CoreCLR path. 
```

**Comment by agracio** [comment]
This is strange it did work for me before but no longer works regardless of Edge.js version.

**Comment by agracio** [comment]
For now I can advise to deploy published .NET libraries while I am working on unresolved issues, when publishing refer to the comment I mentioned earlier as well as the last comment on the same thread.

**Comment by BeneRasche** [comment]
Created PR with possible fix for the issue

https://github.com/agracio/edge-js/pull/227

**Comment by agracio** [comment]
Did you test it yourself to see if the issue is resolved? I am compiling and testing now.
There is one thing that really bother me about original debug output, this line is generated by `libhost.cpp` and the only callers to that method are in `fx_muxer.cpp` from `get_runtime_config_paths_from_app` and `get_runtime_config_paths_from_app` methods, however trace lines from those call are not printed in debug output.

```
Runtime config is cfg=C:\Program Files\dotnet\sdk\8.0.403\dotnet.runtimeconfig.json dev=C:\Program Files\dotnet\sdk\8.0.403\dotnet.runtimeconfig.dev.json
```

`fx_muxer.cpp`
```cpp
if (runtime_config.empty())
{
    trace::verbose(_X("App runtimeconfig.json from [%s]"), app_candidate.c_str());
    get_runtime_config_paths_from_app(app_candidate, &config_file, &dev_config_file);
}
else
{
    trace::verbose(_X("Specified runtimeconfig.json from [%s]"), runtime_config.c_str());
    get_runtime_config_paths_from_arg(runtime_config, &config_file, &dev_config_file);
}
```

**Comment by BeneRasche** [comment]
I did. I did not want to compile the files myself as creating binaries if you are not the maintainer is always a bit "shady" ;)

It seemed to work for me and resolved my issue.
