### ISSUE TITLE
misleading help for `build.bat`

### ISSUE THREAD

**Issue by cbries** [agracio/edge-js#230]
Just call `build.bat` in tools.
The help message is:

```bash
C:\git\tmp\3rdparty-edge\tools>build.bat
Usage: build.bat debug|release "{version} {version}" ...
e.g. build.bat release "0.8.22 0.10.0"
```

Copy the example and try to execute:
`build.bat release "0.8.22 0.10.0"`

Result:

![image](https://github.com/user-attachments/assets/72c1ae99-e030-43d7-848a-7a7226072ebb)

**Comment by agracio** [comment]
To be fair it has a warning that some of the original documentation from Edge.js is outdated, as it is a fork of https://github.com/tjanczuk/edge.
Now you can only call it with a single Node.js value which can be either a specific version e.g. `build.bat release 20.12.2` or a major version e.g. `build.bat release 20` - in this case build.bat will build the latest available version from major. At the time of this comment it would be 20.18.0.

**Comment by agracio** [comment]
Should be resolved now.
