### ISSUE TITLE
Node 22.11.0 | edge-js 22.9.0 - The edge module has not been pre-compiled for node.js version v22.11.0...

### ISSUE THREAD

**Issue by m4rtelli** [agracio/edge-js#233]
![Screenshot 2024-11-15 at 12 39 54 PM](https://github.com/user-attachments/assets/b271b726-7bcc-43e0-b122-bd2b7588df9f)

Running into an interesting issue. My project currently in production, uses Node v20.9.0 with edge-js v20.10.2 and it runs fine. I am now in the process of upgrading dependencies and initially, I am upgrading to the LTS version of Node (22.11.0). I see that edge-js is already updated to support any minor version of Node v22. However, as seen in the screenshot above, my project fails to run with the typical compilation error we have seen in the past when edge-js doesn't support this version. Now I also did try an earlier version of Node v22 (22.7 to be exact) as a test and that provided a similar error. 

Since you have added support already for Node v22, I'm a bit stuck as to what to do in order to fix this. I looked through some older issues and recognized some users on Next js complaining of something similar. This is not a react or native app though and I am not using Webpack. Any advice would be so terrific. Thanks so much for your time.

**Comment by agracio** [comment]
I think there must have been some kind of problem with your upgrade process. Ty running https://github.com/agracio/edge-js-quick-start.
Btw did you update to latest version of `edge-js`?

**Comment by m4rtelli** [comment]
> I think there must have been some kind of problem with your upgrade process. Ty running https://github.com/agracio/edge-js-quick-start.
> 
> Btw did you update to latest version of `edge-js` in your project?

Thank you for taking the time to respond. I did install the latest version of edge-js for node 22. Version 22.9.0 I believe. I'll redo my setup and try it again.

**Comment by agracio** [comment]
I always recommend the latest edge-js package as it comes with some updates so 23.1.1. is a better option. However any edge-js package that start with 22 supports Node.js 22.x

**Comment by agracio** [comment]
Any luck?

**Comment by m4rtelli** [comment]
Was just about to update :). Looking good. Apologies for the false alarm. I'll close this issue.
