### ISSUE TITLE
❓Is it possible to use edge-js to integrate the Digital Persona SDK into my Node.js application? 

### ISSUE THREAD

**Issue by alexandergrutstudio** [agracio/edge-js#235]
Is it possible to use edge-js to access the Digital Persona SDK in a Node.js environment? Specifically, I need to be able to compare fingerprints using the SDK made for C# within the Node.js app.

Any help or suggestions on how to approach this integration would be greatly appreciated!

**Comment by agracio** [comment]
It should be possible as long as you reference required dlls. Take a look at https://github.com/agracio/edge-js-quick-start it has examples on how to reference dll.
