### ISSUE TITLE
Documentation for NextJs

### ISSUE THREAD

**Issue by jolic** [agracio/edge-js#237]
The flag 
`experimental: {
    serverComponentsExternalPackages: ....
`
has been removed since v15 and moved to stable, see

https://nextjs.org/docs/app/api-reference/config/next-config-js/serverExternalPackages

For a ts config file in NextJs the config should look like:

```import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: ['edge-js'],
  /* other flags... */
};

export default nextConfig;

**Comment by agracio** [comment]
Updated
