### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ZpmFred** [agracio/edge-js#28]
Hello I have a "little" problem with the ram consumption  of a very simple example:
```
var edge = require('edge-js');

var addAndMultiplyBy2 = edge.func(function () {/*
    async (dynamic input) => {
        var add = (Func<object, Task<object>>)input.add;
        var twoNumbers = new { a = (int)input.a, b = (int)input.b };
        var addResult = (int)await add(twoNumbers);
        return addResult * 2;
    }   
*/});

var payload = {
    a: 2,
    b: 3,
    add: function (data, callback) {
        callback(null, data.a + data.b);
    }
};

function work() {
    for (let i = 0; i < 65536 * 16; i++) {
        addAndMultiplyBy2(payload, function (error, result) {
            if (error) throw error;
        });
    }
}

work();

setTimeout(() => {}, 50000);
```

The ram consumption goes up to about 2GO then never get down until the program closes.
![image](https://user-images.githubusercontent.com/6588387/37786716-a2e342e0-2dfd-11e8-9fd1-c57e1a177e2e.png)

Did I do something wrong, or is there a memory leak?
I use Node V8.10.0 and edge-js 9.3.5

**Comment by agracio** [comment]
I would recommend to compile you C# code into separate .dll and call it from JS code that way. This should allow GC to run correctly.
