### ISSUE TITLE
Azure Web App System.AccessViolationException

### ISSUE THREAD

**Issue by zd-dalibor** [agracio/edge-js#29]
Whenever I upload new version of my application on application reloading I got this error:
```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at EdgeJs.Edge.NodeStartx86(Int32, System.String[])
   at EdgeJs.Edge+<>c__DisplayClass14_0.<Func>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

After that w3wp process restart itself and everything works again.

The same problem I have with IISExpress during development. The same error kills my IISExpress process on every new build.

**Comment by agracio** [comment]
Please refer to this issue: https://github.com/agracio/edge-js/issues/17. Edge.js does not work on IIS except IIS Express, so if it works for you at all could you update the above issue with your IIS config, pool config, permissions, OS, etc... to help people run it on IIS.
AccessViolationEception issue was introduced into original Edge.js repo as part of major code changes in May 2017. `edge-js` includes this PR: https://github.com/tjanczuk/edge/pull/573 that suppose to fix the exception, but it appears to work only in non-IIS scenarios.

**Comment by dalibor983** [comment]
@agracio I am using [EdgeJs 9.3.4](https://www.nuget.org/packages/EdgeJs/) from your repo on .net 4.61.
[Edge.js 8.2.1](https://www.nuget.org/packages/Edge.js/) from 'tjanczuk/edge' does not work at all.

9.3.4 works but crashing on app reloading

**Comment by agracio** [comment]
How about OS and IIS pool configuration? Is IIS pool just a default one?

**Comment by dalibor983** [comment]
@agracio I don't known what azure doing behind webapp service. I only know that at the top is IIS and how  azure configure IIS i don't kown, You can host ASP.NET apps and for nodjs, php and net.core IIS is only a proxy. The only thing I can configure are things in **Web.config** in my application.

**Comment by agracio** [comment]
What about web.config, what kind of configuration you have there?

**Comment by dalibor983** [comment]
@agracio What currently I can conclude is that ```Edge.Func()``` start V8 thread in behind. Is there some way that I can kill that thread manually?

I think that w3wp.exe process does not restart itself on asp.net application reloading so V8 thread is not terminated like it is in desktop applications (the same is with IIS Express).

If there is some method for terminating V8 thread manually I can call it on asp application restart event.

**Comment by dalibor983** [comment]
@agracio [web.config](https://gist.github.com/dalibor983/3d738853bd0264e62b63742f9cb797c7)

**Comment by agracio** [comment]
Could you also share you `IISRewriteRules.config` file

**Comment by dalibor983** [comment]
I switch my application from this repo to [aspnet/JavaScriptServices](https://github.com/aspnet/JavaScriptServices).
So far so good.

**Comment by DoubleCouponDay** [comment]
@agracio I just wanted to thank you for releasing the fix early. My edgejs modules would fail in a unit test and this fork fixed my problems. Can you point to a thread where information on the resolving of these changes will be displayed? (In the original edge.sj repo)

**Comment by agracio** [comment]
Issue fixed in https://github.com/agracio/edge-js/pull/119, please update to newest nuget package.
