### ISSUE TITLE
Who does this "build"/version work's with asp.net?

### ISSUE THREAD

**Issue by pfigueiredo** [agracio/edge-js#3]
I have this issue posted in the "original" edge project.  does your fork resolve this issue?

https://github.com/tjanczuk/edge/issues/578

**Comment by agracio** [comment]
It looks like the issue was introduced in `edge` 7.10.0. You can try, but I do not think that this project resolves it.

**Comment by agracio** [comment]
I have merged https://github.com/tjanczuk/edge/pull/573 fix into this fork. Version 8.2.2 should resolve the issue.
