### ISSUE TITLE
Unable to load DLL 'node.dll' when running using x86 configuration

### ISSUE THREAD

**Issue by kahootali** [agracio/edge-js#31]
I am using EdgeJS 9.3.4 in my Unit Tests, when I run the tests using x64 configuration, it works fine but when I run using x86 build configuration, it gives error:
```
An unhandled exception of type 'System.DllNotFoundException' occurred in EdgeJs.dll
Unable to load DLL 'node.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
The edge folder is being copied to the bin folder and it has the node.dll in the x86 folder.

**Comment by agracio** [comment]
Can you create an example repo that reproduces the issue?

**Comment by efklebba** [comment]
It is quite possible that this is just a problem with the Node.js assembly bitness. We ran into a similar problem creating an x86 vs x64 application using Node.js. You will have to use the 32-bit version of Node.js if you want to use it in an x86 environment. The 64-bit version won't work. Mixing bitness is not allowed.
