### ISSUE TITLE
Where does Console.WriteLine output go?

### ISSUE THREAD

**Issue by lordbah** [agracio/edge-js#38]
In vscode running a Javascript app which uses edge-js to call C# code, where does Console.WriteLine output go? Not in vscode's Debug Console or Output windows.

**Comment by agracio** [comment]
`Console.WriteLine` suppose to go to a console output. Run your app without VSCode and see that it works, otherwise you might not be hitting the code that has `Console.WriteLine`. If it works standalone the issue is with VSCode.

**Comment by HebaruSan** [comment]
Oddly, `Console.WriteLine` works for me while `log4net` is struggling. Luckily either is serviceable for my purposes.
