### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by danielszenasi** [agracio/edge-js#4]
I am using os x Sierra and dotnet. I got the following exception when i try to require edge-js

dotnet --version
2.0.0

Unhandled Exception: System.TypeLoadException: Could not load type 'System.Runtime.Loader.AssemblyLoadContext' from assembly 'System.Runtime.Loader, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by agracio** [comment]
Appears to be specific to 2.0, trying to sort it out.

**Comment by agracio** [comment]
Issue resolved in version [8.2.5](https://www.npmjs.com/package/edge-js) but 2 of .NET Core tests are [failing](https://travis-ci.org/agracio/edge-js/jobs/276336295). I will keep investigating, in the meantime please use v8.2.5 and let me know if you have any issues.
