### ISSUE TITLE
.net standard (possible?) issue

### ISSUE THREAD

**Issue by grofit** [agracio/edge-js#40]
I have seen a few threads in here and they all point to the quick start apps (of both edge and edge + electron variety).

Now I have followed those as far as I can tell i.e

```ts
export const assemblyDir = `${path.resolve(process.cwd(), "dist/assemblies")}`;

process.env.EDGE_USE_CORECLR = <any>1;
process.env.EDGE_APP_ROOT = assemblyDir;

import {func} from "electron-edge-js";
```

This all works fine for simple use cases, but when I start referencing .net standard dlls (2.0) it starts falling over with errors like:

```
error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. 
You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

I noticed that there are a few threads specifically around .net standard but most of them either point to your quick start (which was referenced for this) or just mention you need to include all dependent DLLs for the dll you are trying to import.

So I have done as mentioned in the quick start and made sure I add the relevant bits in the csproj to output all the relevant dlls etc and have them in the same dir as the assembly that is loaded. That didnt work, I also added some config to tell it to output the underlying dlls like `netstandard.dll` etc and they come out in a `ref` folder, tried adding that too as well as just dumping ALL of the contents of those folders into the same one, still same issue.

Here is what the csproj currently looks like:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.7.0" />
    <PackageReference Include="NETStandard.Library" Version="2.0.0" />
  </ItemGroup>

</Project>
```

I have added the `PreserveCompilationContext` and the PackageReference to `NETSTandard.Library` just to see if I could get it working, but am at a loss.

So was wondering if you have seen anything like this before?

I am assuming that:

- I am telling it to use CoreCLR correctly (is there any way to confirm it is using that on the output?)
- I am providing the relevant dependencies for my dll

Any help or advice would be great, and I am sure this is an issue with me not the project but am at a bit of a loss as to where to turn.

**Comment by agracio** [comment]
Take a look at this sample: https://github.com/agracio/electron-edge-js-quick-start

**Comment by grofit** [comment]
As mentioned in the post I have looked over both quick starts and scoured the Internet for info but nothing seems to touch upon the specifics as to why it isn't working.

Your quick starts also target coreapp not standard 2, so it's not exactly the same scenario. 

I have ensured same sdk and project settings (where relevant) building in vs 2017 and am setting the flag for coreclr. 

If you can be more specific in which part of the quick start would help I am happy to look over it again.

**Comment by grofit** [comment]
Have got some progress but a few things seem odd:

- Webpack is doing some weird stuff to `process.env` calls I have had to wrap them to get them to be run correctly, this has changed the error to now just complain that it cannot find `System.Runtime 4.2.0.0`

- The quickstart example is basically exposing a class library (`ExternalLibrary`) but its being built as if it a console application, rather than .net standard, I have tried running the quick start app (which works) but the moment I use inline methods or set the projects to be .net standard, the quick start app breaks too.

**Comment by agracio** [comment]
Both `edge-js` and `electron-edge-js` have been updated to support .NET Standard.
For reference take a look at updated https://github.com/agracio/electron-edge-js-quick-start and https://github.com/agracio/edge-js-quick-start
