### ISSUE TITLE
Does passing Nodejs Buffer to DotNet and passing DotNet byte array back to Nodejs involve copying data?

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [agracio/edge-js#42]
I want to use some code in C# that can take a large array and compress/decompress it, then return another array. So does the marshalling process clone the array, or it just copy the reference/pointer of array?

**Comment by agracio** [comment]
I don't have an answer to that, you will have to check C++ code.

**Comment by Meigyoku-Thmn** [comment]
Well it seems edgejs copies everything that is passed.
https://github.com/agracio/edge-js/blob/master/src/dotnet/clrfunc.cpp#L244
So for large buffer, maybe I have to use callback and pass the buffer pointer.
