### ISSUE TITLE
Deserialize dynamic input to strongly typed c# object

### ISSUE THREAD

**Issue by stephen776** [agracio/edge-js#43]
Is there any method or example of automatically deserializing the dynamic input parameters to an object we can define in c#? perhaps a library like JSON.NET or similar that can be plugged in?

```
public async Task<object> MyMethod(dynamic input)
{
    //Want to deserialize "input" to a real object
    //something like...
    var myObject = Deserialize<MyType>(input);
}

```

**Comment by stephen776** [comment]
started playing with a way to do it with reflection and generics. This early iteration may be naive...but could potentially be expanded to handle everything I need....assuming there is no better way that someone may know of:

```
//Method to deserialize dynamic input to their proper types
        private T Deserialize<T>(IDictionary<string, object> input)
            where T : new()
        {
            var result = new T();

            foreach(var prop in typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {                
                var propName = prop.Name.ToString();
                var propType = prop.PropertyType;

                //get prop value from input
                var value = input[propName];

                if(prop.PropertyType.IsEnum)
                {
                    //special case for enum
                    value = Enum.Parse(propType, value.ToString());
                }

                prop.SetValue(result, value);
            }

            return result;
        }
```

**Comment by agracio** [comment]
This is outside of scope of `edge-js`. But if you are looking at deserialising JSON javascript objects into C# the easiest way would be to use JSON.NET `DeserializeObject` method.
```csharp
var myObject = JsonConvert.DeserializeObject<MyObjectType>(jsonstring);
```

**Comment by stephen776** [comment]
Well, more specifically I was to deserialize the `dynamic` input parameter that is required in an edge.js function on the .net side to a real object.

**Comment by stephen776** [comment]
using JSON.NET if you try this: 

```
var json = JsonConvert.SerializeObject(input);
var myClass = JsonConvert.DeserializeObject<MyClass>(json);
```

you get the error:
`Serializing delegates is not supported on this platform.`

**Comment by agracio** [comment]
As per my previous comment this is outside of scope of Edge.js and comes down to a pure C# problem.
Converting the object to dictionary should be the first step, but from there it is up to you how to use it.

```csharp
public async Task<object> MyMethod(dynamic input)
{
    var dictionary = (IDictionary<string, object>) input;
}
```

Try looking at ExpandoObject as well https://stackoverflow.com/questions/36557845/can-one-convert-a-dynamic-object-to-an-expandoobject-c.

But you will have to live with this limitation of Edge.js.

**Comment by efklebba** [comment]
stephen776,

I did something similar using edge-js to connect a 64-bit app to a 32-bit dll using a DataContract. You can check out this solution using Visual Studio 2015 (https://github.com/efklebba/AccessX86FromX64).

The key was these two lines:
   JavaScriptSerializer sr = new JavaScriptSerializer();
   CalculatorInput calculatorInput = sr.Deserialize<CalculatorInput>(inputData.Object);

The dynamic object is passed in as the inputData object.
