### ISSUE TITLE
Packages in ~/.nuget cannot be resolved in Linux

### ISSUE THREAD

**Issue by westonpace** [agracio/edge-js#46]
There are a number of `#if EDGE_PLATFORM_NIX` statements in `deps_entry.cpp` which control lowercasing path names.  However, in `deps_entry.h` there is the following code:

```
#if EDGE_PLATFORM_NIX
#include "../edge.h"
#endif
```

The problem is `EDGE_PLATFORM_NIX` will only be defined if `edge.h` is already loaded.  Since it is not defined then `edge.h` is not loaded and `EDGE_PLATFORM_NIX` is never defined.

If I remove the `#if` from `deps_entry.h` then everything starts working on Linux.  However, I am presuming it was put in there for a reason and I don't know that reason so I'm not sure what a proper fix would be.

**Comment by westonpace** [comment]
The error that you get is identical to https://github.com/agracio/edge-js/issues/26 and may be what @wangyiwen0972 encountered.

**Comment by agracio** [comment]
You do not need to set `EDGE_PLATFORM_NIX` variable to run on linux. Take a look at this example that runs on Windows/macOS/Linux: https://github.com/agracio/edge-js-quick-start.

**Comment by westonpace** [comment]
I get a segmentation fault when I try and run that example on a pretty fresh Ubuntu 18.04 VM.  I can dig into that more.

I get that you should not have to set `EDGE_PLATFORM_NIX` because it should be set automatically (in `edge_common.h` because `__linux` is defined).  But, in `deps_entry.cpp` it never includes `edge_common.h` because `EDGE_PLATFORM_NIX` isn't set yet.

**Comment by agracio** [comment]
Thats what i tested it on, 18.04 VM. make sure you have the pre-requisites installed, take a look at this docker container spec: https://github.com/agracio/docker-ubuntu-node-netcore/blob/master/Dockerfile

**Comment by westonpace** [comment]
Here is the entire output from my test on your Dockerfile:

https://pastebin.com/TyXhL9Hj

When I run `npm start` I get:
```

root@02283e486ed2:/test/edge-js-quick-start# npm start
 
> edge-js-quick-start@1.0.0 start /test/edge-js-quick-start
> node main.js core
 
Segmentation fault (core dumped)
```

**Comment by westonpace** [comment]
I have figured out the cause of the segmentation fault but it is just masking another image.  I will create a PR with a fix for that issue. and get the logs of the next error in a moment.

**Comment by westonpace** [comment]
Ok, the segmentation fault is addressed by https://github.com/agracio/edge-js/pull/47 but now when I run `npm start` I received the following output:
```

root@02283e486ed2:/test/edge-js-quick-start# npm start

> edge-js-quick-start@1.0.0 start /test/edge-js-quick-start
> node main.js core


module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: Call to coreclr_create_delegate() for GetFunc failed with a return code of 0x80070002.
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/test/edge-js-quick-start/node_modules/edge-js/lib/edge.js:54:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

```

It appears the problem is that the EdgeJs.dll is not being loaded into the created CLR.  The `edge-js-quick-start` appears to be using a custom `.deps` file.  My experiment loaded a default one from `node_modules/edge-js/lib/bootstrap/bin/Release/netcoreapp1.1/bootstrap.deps.json` however in the quick start it is using `src/QuickStart.Core/bin/Debug/netcoreapp2.0/QuickStart.Core.deps.json`.  The former has a reference to the `Edge.Js` and `Edge.Js.CSharp` while the latter does not.

Actually, on further examination, the problem is the order in which I ran the setup steps.  I ran `dotnet build` before I ran `npm install`.  The `QuickStart.Core.csproj` references edge-js as a relative reference into `node_modules` and if `node_modules` doesn't exist then that reference fails with a warning, the project still builds, and you get the error described above.

Once I build everything in the correct order everything works but it is still not using the correct lowercase paths (as evidenced in the EDGE_TEST=1 output).  I will try and figure out how it is still working so I can use that behavior as a workaround.

**Comment by westonpace** [comment]
So basically it works as long as it never has to reference any package from NuGet since the packages installed as part of the runtime have the upper cased named and the packages installed locally have the upper cased names.  I can't figure out the exact permutation of things required but, for example, if you try and run `npm run start:standard` to reference the other project in the quick start it fails.

I haven't been able to get any `netstandard` target to work.

It also fails if I don't have `CopyLocalLockFileAssemblies` set to true.

It also fails if I am using `netcoreapp2.0` but don't add these two dependencies:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.InternalAbstractions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="2.0.0" />
  </ItemGroup>
```

**Comment by westonpace** [comment]
Ok.  I thought this over for a bit and the above caveats are starting to make sense.

- Whatever EDGE_APP_ROOT is set to is going to be the entry point of your application so it makes sense to target `netcoreapp` and not `netstandard`.
- Targetting NuGet packages is probably a bad idea.  It indicates a portability failure and means if you copy your application to a different system it may to fail.  So `CopyLocalLockFileAssemblies` is a good idea.

So I would still suggest fixing the issue originally detected since it NuGet resolution works on Windows and makes sense in a development environment but I think some documentation fix is in order to help describe these issues as well.  I will try and get to that if I have time.

Also, I think the bootstrap project should build with `CopyLocalLockFileAssemblies` set to true.  I will open a separate issue for that discussion.

**Comment by agracio** [comment]
There is also an option to build it as standalone app, with all dependent assemblies distributed with your application. This allows you to copy/distribute you application to any system without the need to install .NET Core on the target machine.

**Comment by westonpace** [comment]
Yes, that workaround would also be effective.  I've updated the title to reflect the symptoms now that I know a little bit more about what is going on.
