### ISSUE TITLE
Bootstrap project should build with CopyLocalLockFileAssemblies set to true

### ISSUE THREAD

**Issue by westonpace** [agracio/edge-js#48]
Currently, when your run `npm install` a bunch of DLLs are copied into the user's nuget folders.  This can cause issues like https://github.com/agracio/edge-js/issues/26 and it means, if the root project folder were moved to a different machine without running `npm install` on the other machine then the code would no longer run (since the other machine would not have the nuget folders).

In the short term this also means that bootstrap won't work on Linux but that can be addressed by https://github.com/agracio/edge-js/issues/46.

If, instead, the `CopyLocalLockFileAssemblies` were set to true then the DLLs would be inside the `node_modules` hierarchy and the bootstrap process would be more portable.

**Comment by westonpace** [comment]
I see the comment but I'm not sure you would want to build the bootstrap project as a standalone application.  I think by default people would expect it to use the dotnet version they have installed.  It makes sense for user apps though.

**Comment by westonpace** [comment]
What is the point of bootstrap then if anything using it can't be distributed?  Is it only for development and testing?  If so, we should probably at least update the documentation to explain this point.

**Comment by agracio** [comment]
It can be distributed as long as you install your app correctly. https://github.com/agracio/edge-js-quick-start can be used by any user as long as the user has pre-requisites installed, the pre-requisites include nuget packages. Don't forget that your app can also depend on other nuget packages, bootstrap cannot solve those dependencies. One of the projects in https://github.com/agracio/edge-js-quick-start could have a dependency on a nuget package too.
