### ISSUE TITLE
AspNetCore 2.0

### ISSUE THREAD

**Issue by windischb** [agracio/edge-js#5]
Hi!

In the readme there is an example -> "You can also script Node.js from C#:"
Is this also possible from AspNetCore 2.0 or only from .Net Framework 4.5+?

**Comment by agracio** [comment]
Hi,
There is a compatibility table at the top of the readme file. Unfortunately scripting Node.js from C# is only supported using .NET 4.5 and although CoreCLR support is listed as 'coming soon' the [original repository](https://github.com/tjanczuk/edge) has hardly seen any activity in the last year, so it is unlikely to be implemented.
