### ISSUE TITLE
Can't build for Node.js 9.11.1

### ISSUE THREAD

**Issue by jahazieldom** [agracio/edge-js#53]
node: 9.11.1
node-gyp: v3.8.0
edge-js: 10.3.1
Windows 7 x64

`node-gyp configure --target=9.11.1 --msvs_version=2015`
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@9.11.1 | win32 | x64
gyp info spawn C:\Users\usuario\.windows-build-tools\python27\python.EXE
gyp info spawn args [ 'C:\\Users\\usuario\\AppData\\Roaming\\nvm\\v9.11.1\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\usuario\\nw-edge-js\\node_modules\\edge-js\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\usuario\\AppData\\Roaming\\nvm\\v9.11.1\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\usuario\\.node-gyp\\9.11.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\usuario\\.node-gyp\\9.11.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\usuario\\AppData\\Roaming\\nvm\\v9.11.1\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\usuario\\.node-gyp\\9.11.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\usuario\\nw-edge-js\\node_modules\\edge-js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\usuario\\nw-edge-js\\node_modules\\edge-js\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
gyp info ok

`node-gyp build --target=9.11.1 --msvs_version=2015`

..\src\CoreCLREmbedding\coreclrfuncinvokecontext.cpp(90): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\edge_coreclr.vcxproj]
  C:\Users\usuario\nw-edge-js\node_modules\nan\nan.h(1655): note: see declaration of 'Nan::Callback::Call'
  coreclrnodejsfuncinvokecontext.cpp
  utils.cpp
  pal_utils.cpp
  trace.cpp
  fx_ver.cpp
  fx_muxer.cpp
  json.cpp
  json_parsing.cpp
c:\users\usuario\nw-edge-js\node_modules\edge-js\src\coreclrembedding\fxr\../host/libhost.h(19): warning C4099: 'fx_ver_t': type name first seen using 'struct' now seen using 'class' (compiling source file ..\src\CoreCLREmbedding\fxr\fx_ muxer.cpp) [C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\edge_coreclr.vcxproj]
  c:\users\usuario\nw-edge-js\node_modules\edge-js\src\coreclrembedding\host\../fxr/fx_ver.h(12): note: see declaration of 'fx_ver_t' (compiling source file ..\src\CoreCLREmbedding\fxr\fx_muxer.cpp)
  json_serialization.cpp
  asyncrt_utils.cpp
  deps_format.cpp
  deps_entry.cpp
  deps_resolver.cpp
  args.cpp
  coreclr.cpp
c:\users\usuario\nw-edge-js\node_modules\edge-js\src\coreclrembedding\host\libhost.h(19): warning C4099: 'fx_ver_t': type name first seen using 'struct' now seen using 'class' (compiling source file ..\src\CoreCLREmbedding\deps\deps_reso lver.cpp) [C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\edge_coreclr.vcxproj]
  c:\users\usuario\nw-edge-js\node_modules\edge-js\src\coreclrembedding\host\../fxr/fx_ver.h(12): note: see declaration of 'fx_ver_t' (compiling source file ..\src\CoreCLREmbedding\deps\deps_resolver.cpp)
  libhost.cpp
c:\users\usuario\nw-edge-js\node_modules\edge-js\src\coreclrembedding\host\libhost.h(19): warning C4099: 'fx_ver_t': type name first seen using 'struct' now seen using 'class' (compiling source file ..\src\CoreCLREmbedding\host\args.cpp)  [C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\edge_coreclr.vcxproj]
  c:\users\usuario\nw-edge-js\node_modules\edge-js\src\coreclrembedding\host\../fxr/fx_ver.h(12): note: see declaration of 'fx_ver_t' (compiling source file ..\src\CoreCLREmbedding\host\args.cpp)
  runtime_config.cpp
  pal.windows.cpp
c:\users\usuario\nw-edge-js\node_modules\edge-js\src\coreclrembedding\host\libhost.h(19): warning C4099: 'fx_ver_t': type name first seen using 'struct' now seen using 'class' (compiling source file ..\src\CoreCLREmbedding\host\libhost.c pp) [C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\edge_coreclr.vcxproj]
  c:\users\usuario\nw-edge-js\node_modules\edge-js\src\coreclrembedding\host\../fxr/fx_ver.h(12): note: see declaration of 'fx_ver_t' (compiling source file ..\src\CoreCLREmbedding\host\libhost.cpp)
..\src\CoreCLREmbedding\host\runtime_config.cpp(41): warning C4996: 'web::json::value::to_string': This API is deprecated and has been renamed to avoid confusion with as_string(), use ::web::json::value::serialize() instead. [C:\Users\us uario\nw-edge-js\node_modules\edge-js\build\edge_coreclr.vcxproj]
  C:\Users\usuario\nw-edge-js\node_modules\edge-js\src\CoreCLREmbedding\json\casablanca\include\cpprest/json.h(431): note: see declaration of 'web::json::value::to_string'
     Creating library C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\Release\edge_coreclr.lib and object C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\Release\edge_coreclr.exp
  Generating code
  All 4413 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  edge_coreclr.vcxproj -> C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\Release\\edge_coreclr.node
  edge_coreclr.vcxproj -> C:\Users\usuario\nw-edge-js\node_modules\edge-js\build\Release\edge_coreclr.pdb (Full PDB)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\usuario\AppData\Roaming\nvm\v9.11.1\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--target=9.11.1" "--msvs_version=2015"
gyp ERR! cwd C:\Users\usuario\nw-edge-js\node_modules\edge-js
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

C:\Users\usuario\nw-edge-js\node_modules\edge-js (master -> origin) (edge-js@10.3.1)

**Comment by agracio** [comment]
Not sure what you trying to do? Is that an error you getting during `npm install`? This repo already supports Node.js 9.x but you if want to rebuild it yourself please take at `tools/build.bat` for reference. 
As you can see `node gyp` command runs using a specific version of downloaded node.exe rather than `--target`, also `--msvs_version` should be set to 2017.
If you just want to rebuild node for specific version `cd` into `tools` directory and run `build release 9.11.1` using VS 2017 command prompt.

**Comment by jahazieldom** [comment]
Thank's for the response, i am trying to build edge-js for node 9.11.1, npm install it's ok, but when i try to build manually it's fail.

i have tried `build release 9.11.1` and the error:
gyp info using node@9.11.1 | win32 | x64
gyp info spawn C:\Users\usuario\.windows-build-tools\python27\python.EXE
gyp info spawn args [ 'C:\\Users\\usuario\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2017',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\usuario\\nw-edge-js\\node_modules\\edge-js\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\usuario\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\usuario\\.node-gyp\\9.11.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\usuario\\.node-gyp\\9.11.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\usuario\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\usuario\\.node-gyp\\9.11.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\usuario\\nw-edge-js\\node_modules\\edge-js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\usuario\\nw-edge-js\\node_modules\\edge-js\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\usuario\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\usuario\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\usuario\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\usuario\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\usuario\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\usuario\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\usuario\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\usuario\\nw-edge-js\\node_modules\\edge-js\\lib\\native\\win32\\x64\\9.11.1\\node.exe" "C:\\Users\\usuario\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--msvs_version=2017" "-release"
gyp ERR! cwd C:\Users\usuario\nw-edge-js\node_modules\edge-js
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Error building edge.node release for node.js x64 v9.11.1

**Comment by jahazieldom** [comment]
i want to use this module in nwjs, but i can't build the module for my nwjs/node version.
------------------------------------
nwjs version: 0.29.4
node version: 9.11.1
v8: 6.5.254.41
chromium: 65.0.3325.181

**Comment by agracio** [comment]
I can only assume you are missing some build dependencies. I also doubt that you will be able to build it for nwjs that easily. I would expect it to require custom headers for build, something similar to custom build that is required for Eelectron.

**Comment by porsager** [comment]
nwjs up until 0.38.4 (node 12.3.1) works well with edge-js 👍

Just build with nw-gyp eg `nw-gyp rebuild --target=0.38.4`
