### ISSUE TITLE
node v10.x and ubuntu 16.04

### ISSUE THREAD

**Issue by webarchymeta** [agracio/edge-js#54]
tried to run a app server after upgrading node from v8.x to v10.x and got the following exception:
```
  SOLINK_MODULE(target) Release/obj.target/edge_coreclr.node
  COPY Release/edge_coreclr.node
  ACTION binding_gyp_build_managed_target_restore_bootstrap_packages lib/bootstrap/project.lock.json
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
build_managed.target.mk:13: recipe for target 'lib/bootstrap/project.lock.json' failed
make: *** [lib/bootstrap/project.lock.json] Error 145
make: Leaving directory '/[local-path]/server-hosts/node_modules/edge-js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-137-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /[local-path]/server-hosts/node_modules/edge-js
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN 1-net-server-hosts@0.0.0 No repository field.
npm WARN 1-net-server-hosts@0.0.0 No license field.
```
on (re)install. I checked, the `edge_coreclr.node` and `edge_nativeclr.node` were generated. When run, the following runtime error was encountered:
```
ubuntu-d-64:/[local-path]/server-hosts$ node app.js
Stacktrace:

/proc/self/maps:
00400000-022a1000 r-xp 00000000 08:01 958084                             /usr/bin/node
024a0000-024a1000 r--p 01ea0000 08:01 958084                             /usr/bin/node
024a1000-024b7000 rw-p 01ea1000 08:01 958084                             /usr/bin/node
024b7000-024d1000 rw-p 00000000 00:00 0 
04396000-046a8000 rw-p 00000000 00:00 0                                  [heap]
41990000-419a0000 rwxp 00000000 00:00 0 
41b25000-41b35000 rwxp 00000000 00:00 0 
be6bc00000-be6bc80000 rw-p 00000000 00:00 0 
11ac1180000-11ac1200000 rw-p 00000000 00:00 0 
23aa8480000-23aa8500000 rw-p 00000000 00:00 0 
34def180000-34def200000 rw-p 00000000 00:00 0 
492f8800000-492f8880000 rw-p 00000000 00:00 0 
74920f80000-74921000000 rw-p 00000000 00:00 0 
7f890280000-7f890300000 rw-p 00000000 00:00 0 
83cd7580000-83cd7600000 rw-p 00000000 00:00 0 
859a4cf6000-859a4cf8000 ---p 00000000 00:00 0 
859a4cf8000-859a4d00000 rw-p 00000000 00:00 0 
859a4d00000-859a4d02000 ---p 00000000 00:00 0 
949e9f00000-949e9f80000 rw-p 00000000 00:00 0 
b4819000000-b4819039000 rw-p 00000000 00:00 0 
be8ec080000-be8ec100000 rw-p 00000000 00:00 0 
e2be0280000-e2be0300000 rw-p 00000000 00:00 0 
e3eb9f00000-e3eb9f80000 rw-p 00000000 00:00 0 
f2c22e00000-f2c22e80000 rw-p 00000000 00:00 0 
104bb6500000-104bb6580000 rw-p 00000000 00:00 0 

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
```

By the way, I had both mono 5.16 and .net core 2.1 installed on the Ubuntu box. And the Windows 10  (64bit, node 10.12) version of edge-js works as expected.

Is support for node 10.x on Linux still lacking or is it a bug somewhere? It's about to becomre LTS. I noticed that node 10 is not listed in the release package ...

**Comment by agracio** [comment]
Node 10.x is supported, you can see latest Ubuntu build on Travis here: https://travis-ci.org/agracio/edge-js/jobs/391909281. Your error indicates that there is something wrong with .NET Core

**Comment by punisher97** [comment]
Hi, i had the same problem, i see Docker by fork edge and update mono version to 5.10, i share my docker file:

`FROM node:10.16.3-slim 
WORKDIR /usr/src/app

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Install Mono 5.10 to work with edge-js
RUN set -eux && export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    # Install authorization and repository
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
    apt install  -yq  apt-transport-https ca-certificates && \
    echo "deb https://download.mono-project.com/repo/ubuntu stable-wheezy/snapshots/5.10 main" | tee /etc/apt/sources.list.d/mono-official-stable.list && \
    apt update && \
    # Install mono 5.10
    apt-get -y install mono-complete && \
    # Install dependecies packages
    apt-get -y install python curl g++ pkg-config libgdiplus  libglib2.0-dev libunwind8 libssl-dev make gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev unzip && \
    # Cleanup the Dockerfile
    apt-get clean && \
    rm -rf /var/lib/apt/lists

COPY package*.json ./
RUN yarn config set ignore-engines true
RUN yarn install

COPY . .

CMD [ "yarn","start:prod" ]`
