### ISSUE TITLE
Lazy symbol binding failed

### ISSUE THREAD

**Issue by jimdubbs** [agracio/edge-js#6]
I get the below error when trying to run the hello world example.
NodeJS: 8.2.1
Mono: 4.2.4
.NET Core 2.0

Everything installed fine. Any insight as to whats causing this?

dyld: lazy symbol binding failed: Symbol not found: _mono_config_parse
  Referenced from: /Users/jimmywestcott/GitHub/Quorum/Quorum-seed/node_modules/edge-js/build/Release/edge_nativeclr.node
  Expected in: flat namespace

**Comment by agracio** [comment]
Mono runtime has been broken since May 5th and May 7th commints into the original repo: https://github.com/tjanczuk/edge/commits/master. I would suggest using .NET Core instead. Set EDGE_USE_CORECLR=1 flag and give it another try.
