### ISSUE TITLE
Content Files in the 'Edge' folder are not copied to the output folder when building

### ISSUE THREAD

**Issue by lincoln42** [agracio/edge-js#64]
**Environment:**
OS: Windows 10
.Net Framework: 4.5.2
EdgeJS Version: 9.3.4
IDE: Visual Studio 2017
Nuget Version: 4.9.2.5706
CPU Architecture: Any CPU

**Issue:** 
After installing EdgeJS in the environment above into a Console simple application using NuGet the project builds just fine. However, when I attempt to run the executable I get an error that says the 'node.dll' is not found.
  After examining the package structure I found that the required files exist under '../content/edge'
in the downloaded package.
  I also found that with NuGet v3 and higher the 'Install.ps1' script that would have marked these files as content files to be copied always to the output will not be run anymore. So for NuGet v3 and higher an alternative solution is needed.
Another Nuget package based on EdgeJS (_https://www.nuget.org/packages/Edge.js.Binaries/_) resolves this issue by specifying build targets for the package in a 'build' folder for the package. These build targets copy the 'content' files required into the output folder on build as well as create links to the 'content' files in the project to allow for debugging and this works for nuget v3 and above and with the new .csproj format with package references in VS2017. 
    Altering the package for this project locally and introducing the 'build' with the below content in a 'EdgeJs.targets' file solves this above issue for this project as well and the necessary content files are copied to the output folder when using nuget v3 and above and the new .csproj format for VS2017.

````
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ContentFolder>$(MSBuildThisFileDirectory)..\content</ContentFolder>
  </PropertyGroup>
  <ItemGroup>

    <!-- For all scripts and binaries -->
    <Content Include="$(ContentFolder)\edge\**\*.*">
      <!-- Copy to output directory on build -->
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <!-- Make link into the project root for debugging -->
      <Link>$(ContentFolder)\edge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <Visible>true</Visible>
    </Content>

  </ItemGroup>
</Project>
````
I would like to suggest that this fix be included for this project to allow the NuGet package to be installed correctly when using NuGet v3 and higher with the new .csproj format in VS2017. I can submit a pull request with the necessary changes if there are no issues with this solution.

**Comment by ViceIce** [comment]
The native dll's should be put in the runtimes folder

see https://dev.to/jeikabu/nupkg-containing-native-libraries-1576

**Comment by agracio** [comment]
Can you submit a PR?

**Comment by ViceIce** [comment]
Sure, but earliest on next week.

**Comment by agracio** [comment]
Done and published to Nuget.

**Comment by fraguada** [comment]
Seems the path is not correct. I get errors when installing nuget package through packages.config (and similarly when testing as packagereference in csproj). Errors are all `Unable to copy file` for all of the files:
```
Error		Unable to copy file "C:\{pathtomyproject}\packages\EdgeJs.11.3.2\content\edge\double_edge.js" to "bin\Debug\C:\{pathtomyproject}\packages\EdgeJs.11.3.2\build\..\content\edge\double_edge.js". The given path's format is not supported.			
```

**Comment by agracio** [comment]
To be honest I just used your script without testing it, can you test it and let me know what changes are needed?

**Comment by agracio** [comment]
Or maybe I can restructure it and make it look like `Edge.js.Binaries` and use the same targets file.

**Comment by lincoln42** [comment]
@agracio You could just use the solution I outlined above but using the 'runtimes' folder as suggested above by @fraguada,I tested it locally before I made the suggestion and it works and is similar to the approach taken by Edge.js.Binaries

**Comment by agracio** [comment]
@lincoln42 I used your `targets` script from the post above.

**Comment by vsilvar** [comment]
@agracio I updated the target in my PR because it appeared to be trying to copy the files to an incorrect path.

I haven't looked into the `runtimes` folder solution and don't know if it's a better option,
but for now the target works.

**Comment by agracio** [comment]
New package published to nuget using https://github.com/agracio/edge-js/pull/74 please test.

**Comment by fraguada** [comment]
The mechanics of the latest nuget package (11.3.3) seem to work. (Getting `Edge.Func()` to work is another issue!)
