### ISSUE TITLE
Unexpected,with for loop hangs

### ISSUE THREAD

**Issue by whiter001** [agracio/edge-js#65]
code:
```javascript
var edge = require('edge-js');
var helloWorld = edge.func(`
    async (input) => {
        for(var i=0;i<1e10;i++){}
        return ".NET Welcomes " + input.ToString(); 
    }
`);
 
helloWorld('JavaScript', function (error, result) {
    if (error) throw error;
    console.log(result);
});
```
when i < 1e9 can run on my pc
if run i < 1e10 hangs...

**Comment by agracio** [comment]
What is the purpose of this code?

**Comment by whiter001** [comment]
No, just a boring  test;
Now I tried the c++ plugin for nodejs with simple code and found that there is something wrong with this, not the problem with this library;
in cpp Addons code:
```c++
  int haha = 0; 
  for(int i =0;i<1e10;i++){haha = i;}
```
This library reminds me of jsc.exe; I think in addition to extending the system capabilities, there should be performance improvements for time-consuming high CPU applications; so...
