### ISSUE TITLE
cannot find node-gyp at ...\node_modules\node-gyp\bin\node-gyp.js

### ISSUE THREAD

**Issue by BlenderViza** [agracio/edge-js#67]
The file node-gyp.js is there!

**Comment by BlenderViza** [comment]
It's not there. The full path is

C:\Users\RVPHX\### **_AppData\Roaming\npm_**\node_modules\node-gyp\bin\node-gyp.js

This path can't be correct.

**Comment by BlenderViza** [comment]
I copied node_modules from Program Files to AppData....   7307 files 512 MB

build.bat release 11.10.1 => success building edge.node

Something ist wrong!

**Comment by BlenderViza** [comment]
My helloWorld example works only if I save it in the folder C:\Users\RVPHX\ AppData\Roaming\npm. 

That's not what I exspected and really really weird. 

Why is everything redirected from the original installation path to AppData\Roaming\npm?

**Comment by agracio** [comment]
The path appears to be correct for global NPM modules. When using default Nide.js installation it should work using the above path. Edge.js will always try to resolve path from AppData and that is not always correct for some types of Node.js install. There is a PR on `electron-edge-js` that resolves that problem, I just need to merge it to both repos.

**Comment by agracio** [comment]
Just realised that you are not following README for building Edge.js. If you want to build it you need to install node-gyp using `nom i -g node-gyp`, that will put it into AppData path.

**Comment by peter-sabath** [comment]
Nearly every package that needs node-gyp requires it to be installed at a global level.
The PR from me agracio mentions is only required if you use multiple node.js versions side-by-side (e.g. using nvm)

**Comment by agracio** [comment]
I think the confusion comes from the fact that Node.js ships with node-gyp installed and I have seen a few posts that say to use Node.js node-gyp rather than install global.
