### ISSUE TITLE
GUI binding framework

### ISSUE THREAD

**Issue by qrzychu** [agracio/edge-js#68]
Hi, I like the idea of Edge.js very much, especially that .NET Core is on a steady rise.

I have found [Coldstone](https://github.com/srakowski/coldstone), proof on concept that it is possible to create MVVM GUI framework like WPF, but one that uses HTML for the views and `ViewModels : INotifyPropertyChanged`.

Do you know if someone is working on something like that? Or maybe it already exists? 

It would be great to pack such app in Electron and not have to fight with JavaScript.

**Comment by agracio** [comment]
Take a look at this repo: https://github.com/ElectronNET/Electron.NET

**Comment by qrzychu** [comment]
Yes, I am aware of that, but this is just RESTfull web app embedded in Electron. 

I was hoping for MVVM framework, where html stands just for the V

**Comment by agracio** [comment]
ASP.NET is an MVC framework so I am not sure why it does not satisfy your requirements. I might be wrong but MVVM pattern was only used in WPF while other frameworks have different patterns like MVC etc..

**Comment by qrzychu** [comment]
Because in MVC I need to do REST call everytime something changes in the  UI. I much prefer WPF way of bindings directly between the View and ViewModel. 

In MVC case I need to build both front-end and back-end just to echo something that user put in TextBox. When I want to do form validation I have to make it twice: once in UI for responsivness, second time in backend for safety. 

It's possible, but I would still prefer MVVM.

**Comment by qrzychu** [comment]
For everyone coming here and not having the answer, there is one in development: [https://dotnet.microsoft.com/apps/aspnet/web-apps/client](https://dotnet.microsoft.com/apps/aspnet/web-apps/client)

You can run C# within the web browser via WebAssembly - package the app with Electron and you have cross platform app
