### ISSUE TITLE
External DLL cannot load

### ISSUE THREAD

**Issue by Mathavana** [agracio/edge-js#70]
Hi,

I have a Node.js application, using edge-js to call C# method.

![image](https://user-images.githubusercontent.com/5356325/56020557-00895f80-5d3a-11e9-9ed2-7a39a8c582fe.png)

Inside my Node.js application folder, copied **Telerik.Reporting.dll**, it is used by **Test.Reporting.dll**

I am getting the following error.
Could not load file or assembly 'Telerik.Reporting, Version=12.2.18.912, Culture=neutral, PublicKeyToken=a9d7983dfcc261be' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))

**Environment Details**

1. Windows 2008R2
2. .NET 4.5

**Comment by Mathavana** [comment]
Also tried to verify via a .net Console application to test the report generation.
My Test program included **Test.Reporting.dll, Test.Reporting.BillingAnalysis.dll, Telerik.Reporting.dll**
Console application able to generate the report.

**Comment by Mathavana** [comment]
Manually register the DLL to GAC, works fine.

**Comment by RSS1102** [comment]
> Manually register the DLL to GAC, works fine.

To place in the root directory,（the root directory of the project    "/"）
