### ISSUE TITLE
disabling dotnet core compile

### ISSUE THREAD

**Issue by fforjan** [agracio/edge-js#71]
In my company, we do not use nuget.org for storing our nuget package and consuming :
For IP and licensing reason, we are white listing them and the access to nuget.org is disabled

At the moment, when we do a `npm ci`, it will detect dotnet in our path and will try to compile and will fail due to the non-access to nuget.org

Is there a simple way to disable dotnet core build at npm install time ?
Our current way is to remove c:\program files\dotnet from the environment variable path when doing `npm ci` but this is a bit ugly :-/

**Comment by agracio** [comment]
Edge.js does not work without compiling. I am also not sure why you would disable nuget.org for licensing reason but not disable npm for same reasons. Just saying.
