### ISSUE TITLE
Console stdout, stdin, stderr

### ISSUE THREAD

**Issue by koltyakov** [agracio/edge-js#76]
First off, thank you @agracio for continuing this project after Tomasz!
I have a question. When running Node.js code in .Net console application, no stdout, stdin, stderr streams are bypassed. In former EdgeJs it was possible to interact with Node.js process using stdin/out. However, in all edge-js's versions this feature is missed. Is it by design now?

**Comment by agracio** [comment]
I am not aware of any changes that would cause that behavior in edge-js, have you tried running the same code side by side using both projects?

**Comment by koltyakov** [comment]
Yes, tried on the same code in the same solution by switching one nuget to another (Edge-Js). When switching to a "headless" mode in the app I'm getting the result from Node.js side so I know the switch to Edge-Js was generally successful, but console stdout/in/err is completely locked - just silence.

**Comment by agracio** [comment]
Unfortunately I have no idea what changes might have contributed to this.
