### ISSUE TITLE
Still work in a Docker container?

### ISSUE THREAD

**Issue by jjasonclark** [agracio/edge-js#84]
I'm having issues using Edge-js in a Debian 9 Docker container. Does anyone know what I've done wrong? Any help would be appreciated. I assume Edge-js still works with Dotnet Core CLR and Node 10.

I've created a git repo at https://github.com/jjasonclark/ole-db-demo

The error is this
```
Error: assembly specified in the dependencies manifest was not found -- package: 'Microsoft.CSharp', version: '4.5.0', path: 'lib/netstandard1.3/Microsoft.CSharp.dll'
/app/node_modules/edge-js/lib/edge.js:180
    return edge.initializeClrFunc(options);
                ^

TypeError: edge.initializeClrFunc is not a function
```

The repo has `npm run build` to create the Docker image. And `npm run start-docker` to run it.

**Comment by agracio** [comment]
Dockerfile updated for Ubuntu 20.04, tested with latest https://github.com/agracio/edge-js-quick-start.
