### ISSUE TITLE
Edge.Func(...) hangs when running/debugging app in linked folder

### ISSUE THREAD

**Issue by peter-hartmann-emrsn** [agracio/edge-js#9]
Using Edge.js.8.2.1 I can reliably reproduce a hanging Edge.Func(...) call when running/debugging my executable through a linked folder. Since our build setup depends on symlinks this is kind of a big deal for us. E.g.:

Have:
```
c:\bin\ConsoleAppUsingEdgeJS.exe
c:\bin\edgejs.dll
c:\bin\edgejs\...
d:\symlink2bin\
```

Now run:
```
c:\bin\ConsoleAppUsingEdgeJS.exe           <-- all good
d:\symlink2bin\ConsoleAppUsingEdgeJS.exe   <-- hangs
```

Similar in VS2015 Project for ConsoleAppUsingEdgeJS when debugging:
```
if exe was build with build output path set to c:\bin\          <-- all good while debugging
if exe was build with build output path set to d:\symlink2bin\  <-- Edge.Func never returns
```

Is there any workaround that makes symlinks work?  Or any hint what the issue could be?

**Comment by agracio** [comment]
If I understand correctly this PR is related to the problem: https://github.com/agracio/edge-js/pull/11. I am yet to test it, but hoping to complete it this weekend.

**Comment by peter-hartmann-emrsn** [comment]
Yes Michael's PR will fix this issue assuming the current directory is set to the path where edgejs.dll is located at first Edge.Func call when the initialization happens.
